export {
  Pagination,
  PaginationEllipsis,
  PaginationItem,
  PaginationItems,
  PaginationList,
  PaginationNext,
  PaginationPrevious,
  PaginationRoot,
  type PaginationEllipsisProps,
  type PaginationItemProps,
  type PaginationItemsProps,
  type PaginationListProps,
  type PaginationNextProps,
  type PaginationPreviousProps,
  type PaginationRootProps,
  type PaginationSize,
  type PaginationVariant,
} from "./Pagination.js";
