export {
  ScrollArea,
  ScrollAreaRoot,
  ScrollAreaViewport,
  ScrollAreaRootProvider,
  ScrollAreaContent,
  ScrollAreaScrollbar,
  ScrollAreaThumb,
  ScrollAreaCorner,
  ScrollAreaContext,
  useScrollArea,
  type ScrollAreaRootProviderProps,
  type ScrollAreaContentProps,
  type ScrollAreaScrollbarProps,
  type ScrollAreaThumbProps,
  type ScrollAreaCornerProps,
  type ScrollAreaSize,
  type ScrollAreaScrollShadow,
  type ScrollAreaController,
  type UseScrollAreaProps,
  type ScrollAreaScrollToDetails,
  type ScrollAreaScrollToEdgeDetails,
  type ScrollAreaScrollbarState,
  type ScrollAreaState,
  type ScrollAreaAxis,
  type ScrollAreaEdge,
  type ScrollAreaIds,
  type ScrollAreaOrientation,
  type ScrollAreaRootElement,
  type ScrollAreaRootProps,
  type ScrollAreaScrollbarGutter,
  type ScrollAreaScrollbarVisibility,
  type ScrollAreaViewportElement,
  type ScrollAreaViewportProps,
} from "./ScrollArea.js";
