import { createRef } from "react";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { Combobox, type ComboboxShape, type ComboboxSize, type ComboboxVariant } from "../../../src/combobox.js";
import { Field } from "../../../src/field.js";

const options = [{ value: "boston", label: "Boston" }, { value: "chicago", label: "Chicago" }, { value: "denver", label: "Denver", disabled: true }];
function Example({ defaultOpen = false }: { defaultOpen?: boolean }) { return <Field.Root id="combobox-city"><Field.Label>City</Field.Label><Combobox.Root defaultOpen={defaultOpen} options={options}><Combobox.Control><Combobox.Input /><Combobox.Clear /><Combobox.Trigger /></Combobox.Control><Combobox.Portal disabled><Combobox.Content><Combobox.Listbox>{options.map(option => <Combobox.Item disabled={option.disabled} key={option.value} label={option.label} value={option.value}>{option.label}</Combobox.Item>)}<Combobox.Empty /><Combobox.Loading /></Combobox.Listbox></Combobox.Content></Combobox.Portal></Combobox.Root></Field.Root>; }

describe("Combobox", () => {
  it("renders canonical recipes and styled anatomy", () => { render(<Example defaultOpen />); expect(screen.getByRole("combobox", { name: "City" })).toHaveClass("brick-combobox-input"); const control = document.querySelector(".brick-combobox-control"); expect(control).toHaveAttribute("data-variant", "outline"); expect(control).toHaveAttribute("data-size", "lg"); expect(control).toHaveAttribute("data-shape", "rounded"); expect(control).toHaveAttribute("data-full-width", ""); expect(screen.getByRole("listbox")).toHaveClass("brick-combobox-listbox"); expect(document.querySelector(".brick-combobox-content")).toHaveAttribute("data-size", "lg"); expect(screen.getAllByRole("option")[0]).toHaveClass("brick-combobox-item"); expect(document.querySelector(".brick-combobox-indicator-artwork")).toBeInTheDocument(); });
  it("exposes variants sizes shapes and intrinsic width without leaking props", () => { const variants: ComboboxVariant[] = ["outline", "soft", "underline"]; const sizes: ComboboxSize[] = ["2xs", "xs", "sm", "md", "lg", "xl", "2xl"]; const shapes: ComboboxShape[] = ["sharp", "rounded", "pill"]; const { rerender } = render(<Example />); for (const variant of variants) { rerender(<Combobox.Root options={options} variant={variant}><Combobox.Control><Combobox.Input aria-label="City" /></Combobox.Control></Combobox.Root>); const control = document.querySelector(".brick-combobox-control"); expect(control).toHaveAttribute("data-variant", variant); if (variant === "underline") expect(control).not.toHaveAttribute("data-shape"); } for (const size of sizes) { rerender(<Combobox.Root options={options} size={size}><Combobox.Control><Combobox.Input aria-label="City" /></Combobox.Control></Combobox.Root>); expect(document.querySelector(".brick-combobox-control")).toHaveAttribute("data-size", size); } for (const shape of shapes) { rerender(<Combobox.Root options={options} shape={shape}><Combobox.Control><Combobox.Input aria-label="City" /></Combobox.Control></Combobox.Root>); expect(document.querySelector(".brick-combobox-control")).toHaveAttribute("data-shape", shape); } });
  it("preserves trigger filtering selection freeSolo and callbacks", async () => { const user = userEvent.setup(); const onValueChange = vi.fn(); render(<Combobox.Root onValueChange={onValueChange} options={options}><Combobox.Control><Combobox.Input aria-label="City" /><Combobox.Trigger /></Combobox.Control><Combobox.Content><Combobox.Listbox>{options.map(option => <Combobox.Item key={option.value} label={option.label} value={option.value}>{option.label}</Combobox.Item>)}</Combobox.Listbox></Combobox.Content></Combobox.Root>); const input = screen.getByRole("combobox"); await user.click(screen.getByRole("button", { name: "Toggle options" })); expect(screen.getByRole("listbox")).toBeInTheDocument(); await user.type(input, "chi"); expect(screen.getByRole("option", { name: "Chicago" })).toBeInTheDocument(); expect(screen.queryByRole("option", { name: "Boston" })).not.toBeInTheDocument(); await user.click(screen.getByRole("option", { name: "Chicago" })); expect(onValueChange).toHaveBeenCalledWith("chicago"); });
  it("preserves refs native props classes and replaceable artwork", () => { const ref = createRef<HTMLInputElement>(); render(<Combobox.Root options={options}><Combobox.Control className="consumer"><Combobox.Input aria-label="City" data-check="yes" ref={ref} /><Combobox.Clear>Remove</Combobox.Clear><Combobox.Trigger aria-label="Open cities"><Combobox.Indicator>Open</Combobox.Indicator></Combobox.Trigger></Combobox.Control></Combobox.Root>); expect(screen.getByRole("combobox")).toBe(ref.current); expect(screen.getByRole("combobox")).toHaveAttribute("data-check", "yes"); expect(document.querySelector(".brick-combobox-control")).toHaveClass("consumer"); expect(screen.getByText("Open")).toBeInTheDocument(); });
  it("inherits Field invalid state on the whole visual control", () => { render(<Field.Root id="invalid-city" invalid><Field.Label>City</Field.Label><Combobox.Root options={options}><Combobox.Control><Combobox.Input /></Combobox.Control></Combobox.Root><Field.Error>Choose a city.</Field.Error></Field.Root>); expect(document.querySelector(".brick-combobox-control")).toHaveAttribute("data-invalid"); expect(screen.getByRole("combobox", { name: "City" })).toHaveAttribute("aria-invalid", "true"); expect(screen.getByText("Choose a city.")).toBeInTheDocument(); });
  it("keeps sparse responsive size metadata on the control and popup", () => { render(<Combobox.Root defaultOpen options={options} size={{lg:"xl"}}><Combobox.Control><Combobox.Input aria-label="City" /></Combobox.Control><Combobox.Content><Combobox.Listbox><Combobox.Item label="Boston" value="boston">Boston</Combobox.Item></Combobox.Listbox></Combobox.Content></Combobox.Root>); expect(document.querySelector(".brick-combobox-control")).toHaveAttribute("data-size","lg"); expect(document.querySelector(".brick-combobox-control")).toHaveAttribute("data-size-lg","xl"); expect(document.querySelector(".brick-combobox-content")).toHaveAttribute("data-size-lg","xl"); });
});
