export {
  Caption,
  Eyebrow,
  Heading,
  Paragraph,
  Text,
  type CaptionProps,
  type EyebrowProps,
  type HeadingLevel,
  type HeadingProps,
  type HeadingVariant,
  type ParagraphProps,
  type ParagraphVariant,
  type TextAlign,
  type TextElement,
  type TextLineClamp,
  type TextProps,
  type TextTone,
  type TextTransform,
  type TextVariant,
  type TextWeight,
  type TextWrap,
} from "./Text.js";
