export {
  Tabs,
  TabsContent,
  TabsIndicator,
  TabsList,
  TabsRoot,
  TabsTrigger,
  type TabsContentInset,
  type TabsContentProps,
  type TabsIndicatorProps,
  type TabsLayout,
  type TabsListColumns,
  type TabsListRadius,
  type TabsListProps,
  type TabsRootProps,
  type TabsSize,
  type TabsTriggerProps,
  type TabsTriggerRadius,
  type TabsVariant,
} from "./Tabs.js";
