export {
  Tabs,
  TabsRootProvider,
  TabsContext,
  TabsContentGroup,
  useTabs,
  useTabsContext,
  type TabsRootProviderProps,
  type TabsContentGroupProps,
  type TabsContentSpacing,
  type TabsContentAnimation,
  type TabsJustify,
  type TabsRecipeProps,
  type UseTabsProps,
  type UseTabsReturn,
  type TabsIds,
  type TabsContextValue,
  TabsContent,
  TabsIndicator,
  TabsList,
  TabsRoot,
  TabsTrigger,
  type TabsContentInset,
  type TabsContentProps,
  type TabsIndicatorProps,
  type TabsLayout,
  type TabsListColumns,
  type TabsListRadius,
  type TabsListProps,
  type TabsRootProps,
  type TabsSize,
  type TabsTone,
  type TabsTriggerProps,
  type TabsTriggerRadius,
  type TabsVariant,
} from "./Tabs.js";
