import { useState, type CSSProperties } from "react";
import { Code, Grid, Icon, Tabs, Text, VStack, type TabsSize, type TabsVariant } from "@flowstack-ui/brick";
import { Scenario, type ScenarioDefinition } from "../../shared/Scenario.js";
import { FormEvidenceCell as Cell, FormEvidenceGroup as EvidenceGroup, FormRenderedOutput as RenderedOutput } from "../../shared/FormEvidence.js";
import { EvidenceSurface } from "../../shared/EvidenceSurface.js";
import { PlaygroundCodeBlock } from "../../shared/PlaygroundCodeBlock.js";
import "../../shared/forms-evidence.playground.css";
import "./tabs.playground.css";

const variants: TabsVariant[] = ["line", "solid", "soft", "enclosed"];
const sizes: TabsSize[] = ["sm", "md", "lg"];
const customStyle = { "--brick-tabs-indicator-color": "#7c3aed", "--brick-tabs-selected-foreground": "#7c3aed", "--brick-tabs-trigger-height": "3.5rem", "--brick-tabs-radius": "0.75rem" } as CSSProperties;

function Star() { return <svg viewBox="0 0 24 24"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9Z" fill="none" stroke="currentColor" strokeLinejoin="round" strokeWidth="1.8" /></svg>; }

function DemoTabs({ ariaLabel, defaultValue = "overview", fullWidth, orientation = "horizontal", size = "md", variant = "line", indicator = variant === "line" }: { ariaLabel: string; defaultValue?: string; fullWidth?: boolean; orientation?: "horizontal" | "vertical"; size?: TabsSize; variant?: TabsVariant; indicator?: boolean }) {
  return <Tabs.Root defaultValue={defaultValue} fullWidth={fullWidth} orientation={orientation} size={size} variant={variant}><Tabs.List ariaLabel={ariaLabel}><Tabs.Trigger value="overview">Overview</Tabs.Trigger><Tabs.Trigger value="activity">Activity</Tabs.Trigger><Tabs.Trigger value="settings">Settings</Tabs.Trigger>{indicator ? <Tabs.Indicator /> : null}</Tabs.List><Tabs.Content value="overview"><Text>Overview panel content.</Text></Tabs.Content><Tabs.Content value="activity"><Text>Activity panel content.</Text></Tabs.Content><Tabs.Content value="settings"><Text>Settings panel content.</Text></Tabs.Content></Tabs.Root>;
}

export const tabsScenarios = [
  { id: "tabs.overview", number: 1, title: "Overview", description: "Tabs defaults to one medium horizontal line list with automatic activation and the first related panel selected." },
  { id: "tabs.variants", number: 2, title: "Variants", description: "Line, solid, soft, and enclosed change only visual treatment while identical tabs and panels remain selected." },
  { id: "tabs.sizes", number: 3, title: "Sizes", description: "Small, medium, and large change shared trigger typography, height, spacing, and panel inset only." },
  { id: "tabs.layout", number: 4, title: "Orientation and width", navigationTitle: "Layout", description: "Vertical orientation changes semantic keyboard direction; full width distributes horizontal triggers equally." },
  { id: "tabs.content", number: 5, title: "Content and states", navigationTitle: "States", description: "Composed icons, long labels, selected state, and disabled state remain aligned without changing defaults unnecessarily." },
  { id: "tabs.activation", number: 6, title: "Activation and panels", navigationTitle: "Behavior", description: "Automatic and manual activation plus mounted and focusable panels expose Atom’s complete behavior without Brick duplication." },
  { id: "tabs.composition", number: 7, title: "Composition", description: "render and asChild replace final hosts while roles, relationships, classes, slots, and selected state remain visible in actual HTML." },
  { id: "tabs.appearance", number: 8, title: "Appearance and customization", navigationTitle: "Theme", description: "Adjacent scopes preserve defaults; one exact custom example matches its supported CSS-variable code." },
  { id: "tabs.stress", number: 9, title: "Responsive and RTL", navigationTitle: "Stress", description: "Constrained horizontal tabs scroll rather than wrap, and RTL reverses horizontal arrow navigation without reversing text." },
] as const satisfies readonly ScenarioDefinition[];

export function TabsPage() {
  const [manual, setManual] = useState("one");
  return <VStack className="forms-page tabs-page" data-component-page="tabs" data-testid="tabs-workbench">
    <Scenario {...tabsScenarios[0]}><EvidenceSurface inset="lg" data-testid="tabs-overview"><DemoTabs ariaLabel="Overview sections" /></EvidenceSurface></Scenario>
    <Scenario {...tabsScenarios[1]}><Grid.Root columns={2} className="forms-grid forms-grid--two" data-testid="tabs-variants">{variants.map((variant) => <Cell key={variant} label={variant}><DemoTabs ariaLabel={`${variant} sections`} variant={variant} /></Cell>)}</Grid.Root></Scenario>
    <Scenario {...tabsScenarios[2]}><Grid.Root columns={3} className="forms-grid forms-grid--three" data-testid="tabs-sizes">{sizes.map((size) => <Cell key={size} label={size}><DemoTabs ariaLabel={`${size} sections`} size={size} /></Cell>)}</Grid.Root></Scenario>
    <Scenario {...tabsScenarios[3]}><Grid.Root columns={2} className="forms-grid forms-grid--two forms-grid--preview-start" data-testid="tabs-layout"><Cell label="vertical"><DemoTabs ariaLabel="Vertical sections" orientation="vertical" /></Cell><Cell label="full width"><DemoTabs ariaLabel="Fitted sections" fullWidth variant="soft" /></Cell></Grid.Root></Scenario>
    <Scenario {...tabsScenarios[4]}><Grid.Root columns={2} className="forms-grid forms-grid--two" data-testid="tabs-content"><Cell label="icon content"><Tabs.Root defaultValue="saved"><Tabs.List ariaLabel="Icon sections"><Tabs.Trigger value="saved"><Icon size="xs"><Star /></Icon>Saved</Tabs.Trigger><Tabs.Trigger value="recent">Recent</Tabs.Trigger></Tabs.List><Tabs.Content value="saved">Saved panel content.</Tabs.Content><Tabs.Content value="recent">Recent panel content.</Tabs.Content></Tabs.Root></Cell><Cell label="disabled"><Tabs.Root defaultValue="ready"><Tabs.List ariaLabel="State sections"><Tabs.Trigger value="ready">Ready</Tabs.Trigger><Tabs.Trigger disabled value="locked">Locked</Tabs.Trigger><Tabs.Trigger value="later">Later</Tabs.Trigger><Tabs.Indicator /></Tabs.List><Tabs.Content value="ready">Ready panel.</Tabs.Content><Tabs.Content value="later">Later panel.</Tabs.Content></Tabs.Root></Cell></Grid.Root></Scenario>
    <Scenario {...tabsScenarios[5]}><Grid.Root columns={2} className="forms-grid forms-grid--two" data-testid="tabs-activation"><Cell label="automatic"><DemoTabs ariaLabel="Automatic sections" /></Cell><Cell label="manual"><Tabs.Root activationMode="manual" value={manual} onValueChange={setManual}><Tabs.List ariaLabel="Manual sections"><Tabs.Trigger value="one">One</Tabs.Trigger><Tabs.Trigger value="two">Two</Tabs.Trigger></Tabs.List><Tabs.Content focusable value="one">Manual panel one.</Tabs.Content><Tabs.Content focusable keepMounted value="two">Manual panel two.</Tabs.Content></Tabs.Root><Text tone="secondary" variant="body-sm">Selected: {manual}</Text></Cell></Grid.Root></Scenario>
    <Scenario {...tabsScenarios[6]}><VStack className="forms-evidence-stack" data-testid="tabs-composition"><EvidenceGroup title="render output" description="The final semantic hosts retain Atom and Brick output."><RenderedOutput label="Rendered Tabs HTML"><Tabs.Root defaultValue="one" render={<section data-adapter="tabs-root" />}><Tabs.List ariaLabel="Rendered sections" render={<nav data-adapter="tabs-list" />}><Tabs.Trigger value="one" render={<button data-adapter="tabs-trigger" />}>One</Tabs.Trigger></Tabs.List><Tabs.Content value="one" render={<div data-adapter="tabs-panel" />}>Panel</Tabs.Content></Tabs.Root></RenderedOutput></EvidenceGroup><EvidenceGroup title="asChild output" description="Consumer hosts receive the same roles and relationships without wrappers."><RenderedOutput label="Composed Tabs HTML"><Tabs.Root defaultValue="one" asChild><section data-adapter="child-root"><Tabs.List ariaLabel="Composed sections" asChild><nav><Tabs.Trigger value="one" asChild><button data-adapter="child-trigger">One</button></Tabs.Trigger></nav></Tabs.List><Tabs.Content value="one" asChild><div data-adapter="child-panel">Panel</div></Tabs.Content></section></Tabs.Root></RenderedOutput></EvidenceGroup></VStack></Scenario>
    <Scenario {...tabsScenarios[7]}><VStack className="forms-evidence-stack"><EvidenceGroup title="Scoped appearances" description="The same line recipe remains coherent in both scopes."><Grid.Root columns={2} className="forms-scoped-grid" data-testid="tabs-appearance"><EvidenceSurface data-brick-appearance="light"><Code>light</Code><DemoTabs ariaLabel="Light sections" /></EvidenceSurface><EvidenceSurface data-brick-appearance="dark"><Code>dark</Code><DemoTabs ariaLabel="Dark sections" /></EvidenceSurface></Grid.Root></EvidenceGroup><EvidenceGroup title="Consumer customization" description="The shown variables exactly produce the purple, taller, rounded line tabs."><EvidenceSurface className="forms-customization" inset="lg"><PlaygroundCodeBlock aria-label="Tabs customization code">{`style={{\n  "--brick-tabs-indicator-color": "#7c3aed",\n  "--brick-tabs-selected-foreground": "#7c3aed",\n  "--brick-tabs-trigger-height": "3.5rem",\n  "--brick-tabs-radius": "0.75rem",\n}}`}</PlaygroundCodeBlock><Tabs.Root defaultValue="overview" style={customStyle}><Tabs.List ariaLabel="Customized sections"><Tabs.Trigger value="overview">Overview</Tabs.Trigger><Tabs.Trigger value="activity">Activity</Tabs.Trigger><Tabs.Indicator /></Tabs.List><Tabs.Content value="overview">Customized panel.</Tabs.Content><Tabs.Content value="activity">Activity panel.</Tabs.Content></Tabs.Root></EvidenceSurface></EvidenceGroup></VStack></Scenario>
    <Scenario {...tabsScenarios[8]}><VStack className="forms-evidence-stack" data-testid="tabs-stress"><EvidenceGroup title="Constrained overflow" description="All labels stay on one row inside a native horizontal scroll region."><EvidenceSurface><div className="tabs-phone"><Tabs.Root defaultValue="overview"><Tabs.List ariaLabel="Constrained sections">{["Overview", "Analytics dashboard", "Team permissions", "Billing history", "Integrations"].map((label) => <Tabs.Trigger key={label} value={label.toLowerCase()}>{label}</Tabs.Trigger>)}</Tabs.List><Tabs.Content value="overview">Overview panel.</Tabs.Content></Tabs.Root></div></EvidenceSurface></EvidenceGroup><EvidenceGroup title="RTL inheritance" description="Genuine RTL labels keep their reading direction while Atom mirrors horizontal arrows."><EvidenceSurface><div className="tabs-phone" dir="rtl"><Tabs.Root defaultValue="one" dir="rtl"><Tabs.List ariaLabel="أقسام الحساب"><Tabs.Trigger value="one">نظرة عامة</Tabs.Trigger><Tabs.Trigger value="two">النشاط</Tabs.Trigger><Tabs.Trigger value="three">الإعدادات</Tabs.Trigger><Tabs.Indicator /></Tabs.List><Tabs.Content value="one">محتوى النظرة العامة.</Tabs.Content><Tabs.Content value="two">محتوى النشاط.</Tabs.Content><Tabs.Content value="three">محتوى الإعدادات.</Tabs.Content></Tabs.Root></div></EvidenceSurface></EvidenceGroup></VStack></Scenario>
  </VStack>;
}
