import { useState, type CSSProperties, type ReactNode } from "react";
import { Button, ContextMenu, Grid, Text, VStack, type ContextMenuSize } from "@flowstack-ui/brick";
import { Scenario, type ScenarioDefinition } from "../../shared/Scenario.js";
import { EvidenceSurface } from "../../shared/EvidenceSurface.js";
import { FormRenderedOutput as RenderedOutput } from "../../shared/FormEvidence.js";
import { PlaygroundCodeBlock } from "../../shared/PlaygroundCodeBlock.js";
import { SpecimenLabel } from "../../shared/SpecimenLabel.js";
import "../../styles/menu-evidence.css";

const sizes: ContextMenuSize[] = ["sm", "md", "lg"];
const customStyle = { "--brick-context-menu-content-radius": "0.25rem", "--brick-context-menu-row-highlighted-background": "#dcfce7", "--brick-context-menu-row-highlighted-foreground": "#166534" } as CSSProperties;
function Group({ children, description, title }: { children: ReactNode; description: string; title: string }) { return <VStack as="section" className="menu-evidence-group"><VStack className="menu-evidence-heading"><Text as="h3" variant="title-sm">{title}</Text><Text as="p" tone="secondary" variant="body-sm">{description}</Text></VStack>{children}</VStack>; }
function Cell({ children, label }: { children: ReactNode; label: string }) { return <EvidenceSurface className="menu-cell" level="canvas"><SpecimenLabel>{label}</SpecimenLabel><div className="menu-preview">{children}</div></EvidenceSurface>; }
function FileContext({ label = "Quarterly report", size = "md", onAction }: { label?: string; size?: ContextMenuSize; onAction?: (value: string) => void }) { return <ContextMenu.Root size={size}><ContextMenu.Trigger asChild><article className="menu-target" aria-label={label} tabIndex={0}><Text>{label}</Text><Text tone="secondary" variant="body-sm">Right-click, press Shift+F10, or touch and hold.</Text></article></ContextMenu.Trigger><ContextMenu.Portal><ContextMenu.Content ariaLabel={`${label} actions`}><ContextMenu.Item onSelect={() => onAction?.("Opened report.")} value="open"><ContextMenu.ItemLabel>Open report</ContextMenu.ItemLabel></ContextMenu.Item><ContextMenu.Item onSelect={() => onAction?.("Report duplicated.")} value="duplicate"><ContextMenu.ItemLabel>Duplicate report</ContextMenu.ItemLabel><ContextMenu.Shortcut>⌘D</ContextMenu.Shortcut></ContextMenu.Item><ContextMenu.Item onSelect={() => onAction?.("Report deleted.")} tone="danger" value="delete"><ContextMenu.ItemLabel>Delete report</ContextMenu.ItemLabel></ContextMenu.Item><ContextMenu.Arrow /></ContextMenu.Content></ContextMenu.Portal></ContextMenu.Root>; }

export const contextMenuScenarios = [
  { id: "context-menu.overview", number: 1, title: "Overview", description: "The default Context Menu adds supplemental target commands without changing the target’s product styling or replacing visible primary actions." },
  { id: "context-menu.invocation", number: 2, title: "Invocation models", navigationTitle: "Invocation", description: "Secondary click, Shift+F10, the Context Menu key, and intentional touch or pen hold open the same command surface." },
  { id: "context-menu.density", number: 3, title: "Density", description: "Small, medium, and large change only the inherited action-menu density." },
  { id: "context-menu.anatomy", number: 4, title: "Item anatomy and grouping", navigationTitle: "Anatomy", description: "Leading content, labels, descriptions, shortcuts, groups, separators, and danger tone use stable logical columns." },
  { id: "context-menu.selection", number: 5, title: "Selection", description: "Checkbox, mixed, and radio state remain application-owned and use automatic indicators." },
  { id: "context-menu.states", number: 6, title: "Content, states, and submenus", navigationTitle: "States", description: "Disabled, danger, long content, and nested commands preserve point positioning and focus behavior." },
  { id: "context-menu.composition", number: 7, title: "Composition and output", navigationTitle: "Composition", description: "asChild and render preserve the authored target host, handlers, refs, slots, and state attributes without adding target paint." },
  { id: "context-menu.appearance", number: 8, title: "Appearance and customization", navigationTitle: "Theme", description: "Scoped appearances preserve the neutral recipe; exact public variables customize only the command surface." },
  { id: "context-menu.stress", number: 9, title: "Responsive, RTL, and preferences", navigationTitle: "Stress", description: "Viewport-edge invocation, mobile long-press cancellation, RTL submenus, reduced motion, and forced colors remain usable." },
] as const satisfies readonly ScenarioDefinition[];

export function ContextMenuPage() {
  const [status, setStatus] = useState("No command selected."); const [pinned, setPinned] = useState(true); const [layout, setLayout] = useState("grid");
  return <VStack className="menu-page" data-component-page="context-menu" data-testid="context-menu-workbench">
    <Scenario {...contextMenuScenarios[0]}><VStack className="menu-evidence-stack"><EvidenceSurface className="menu-overview" inset="lg" data-testid="context-menu-overview"><FileContext onAction={setStatus} /></EvidenceSurface><Button onClick={() => setStatus("Opened report from the visible action.")}>Open report</Button><Text className="menu-status" role="status" tone="secondary" variant="body-sm">{status}</Text></VStack></Scenario>
    <Scenario {...contextMenuScenarios[1]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="context-menu-invocation"><Cell label="pointer and keyboard"><FileContext label="Design proposal" /></Cell><Cell label="touch and pen"><FileContext label="Mobile prototype" /></Cell></Grid.Root></Scenario>
    <Scenario {...contextMenuScenarios[2]}><Grid.Root columns={3} className="menu-grid menu-grid--three" data-testid="context-menu-density">{sizes.map((size) => <Cell key={size} label={size}><FileContext label="Project file" size={size} /></Cell>)}</Grid.Root></Scenario>
    <Scenario {...contextMenuScenarios[3]}><EvidenceSurface className="menu-overview" inset="lg" data-testid="context-menu-anatomy"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="Brand guidelines" tabIndex={0}><Text>Brand guidelines</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="Brand guideline actions"><ContextMenu.Group><ContextMenu.Label>Document</ContextMenu.Label><ContextMenu.Item value="rename"><ContextMenu.Leading aria-hidden="true">R</ContextMenu.Leading><ContextMenu.ItemLabel>Rename document</ContextMenu.ItemLabel><ContextMenu.Description>Change the name visible to collaborators.</ContextMenu.Description><ContextMenu.Shortcut>⌘R</ContextMenu.Shortcut></ContextMenu.Item></ContextMenu.Group><ContextMenu.Separator /><ContextMenu.Item tone="danger" value="delete"><ContextMenu.ItemLabel>Delete document</ContextMenu.ItemLabel></ContextMenu.Item></ContextMenu.Content></ContextMenu.Root></EvidenceSurface></Scenario>
    <Scenario {...contextMenuScenarios[4]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="context-menu-selection"><Cell label="checkbox and mixed"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="Board view" tabIndex={0}><Text>Board view</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="Board options"><ContextMenu.CheckboxItem checked={pinned} onCheckedChange={(next) => setPinned(next === true)} value="pinned"><ContextMenu.ItemIndicator /><ContextMenu.ItemLabel>Pinned board</ContextMenu.ItemLabel></ContextMenu.CheckboxItem><ContextMenu.CheckboxItem checked="indeterminate" value="access"><ContextMenu.ItemIndicator /><ContextMenu.ItemLabel>Inherited access</ContextMenu.ItemLabel></ContextMenu.CheckboxItem></ContextMenu.Content></ContextMenu.Root></Cell><Cell label="radio"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="Layout preview" tabIndex={0}><Text>Layout preview</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="Layout options"><ContextMenu.RadioGroup value={layout} onValueChange={setLayout}>{["list", "grid", "timeline"].map((value) => <ContextMenu.RadioItem key={value} value={value}><ContextMenu.ItemIndicator /><ContextMenu.ItemLabel>{value[0].toUpperCase() + value.slice(1)}</ContextMenu.ItemLabel></ContextMenu.RadioItem>)}</ContextMenu.RadioGroup></ContextMenu.Content></ContextMenu.Root></Cell></Grid.Root></Scenario>
    <Scenario {...contextMenuScenarios[5]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="context-menu-states"><Cell label="states"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="Archived report" tabIndex={0}><Text>Archived report</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="Archived report actions"><ContextMenu.Item value="restore"><ContextMenu.ItemLabel>Restore report</ContextMenu.ItemLabel></ContextMenu.Item><ContextMenu.Item disabled value="share"><ContextMenu.ItemLabel>Sharing unavailable</ContextMenu.ItemLabel></ContextMenu.Item><ContextMenu.Item tone="danger" value="delete"><ContextMenu.ItemLabel>Delete permanently</ContextMenu.ItemLabel></ContextMenu.Item></ContextMenu.Content></ContextMenu.Root></Cell><Cell label="submenu"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="Release notes" tabIndex={0}><Text>Release notes</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="Release note actions"><ContextMenu.Sub><ContextMenu.SubTrigger value="move"><ContextMenu.ItemLabel>Move to folder</ContextMenu.ItemLabel></ContextMenu.SubTrigger><ContextMenu.SubContent><ContextMenu.Item value="product"><ContextMenu.ItemLabel>Product</ContextMenu.ItemLabel></ContextMenu.Item><ContextMenu.Item value="archive"><ContextMenu.ItemLabel>Archive</ContextMenu.ItemLabel></ContextMenu.Item></ContextMenu.SubContent></ContextMenu.Sub></ContextMenu.Content></ContextMenu.Root></Cell></Grid.Root></Scenario>
    <Scenario {...contextMenuScenarios[6]}><VStack className="menu-evidence-stack" data-testid="context-menu-composition"><Group title="Target composition" description="The article remains the only target host and keeps its authored semantics."><RenderedOutput label="Context Menu target HTML"><ContextMenu.Root><ContextMenu.Trigger asChild><article aria-label="Composed report" data-adapter="report-target" tabIndex={0}>Composed report</article></ContextMenu.Trigger></ContextMenu.Root></RenderedOutput></Group><Group title="Visible alternative" description="Important report access remains available as a visible Button beside the supplemental context route."><Button onClick={() => setStatus("Opened from visible alternative.")}>Open selected report</Button></Group></VStack></Scenario>
    <Scenario {...contextMenuScenarios[7]}><VStack className="menu-evidence-stack"><Group title="Scoped appearances" description="Invoke each identical target to compare the neutral surface in local light and dark scopes."><Grid.Root columns={2} className="menu-scoped-grid" data-testid="context-menu-appearance"><EvidenceSurface className="menu-scoped-panel" data-brick-appearance="light"><SpecimenLabel>Light</SpecimenLabel><FileContext label="Light report" /></EvidenceSurface><EvidenceSurface className="menu-scoped-panel" data-brick-appearance="dark"><SpecimenLabel>Dark</SpecimenLabel><FileContext label="Dark report" /></EvidenceSurface></Grid.Root></Group><Group title="Consumer customization" description="The preview changes only documented Context Menu surface variables."><EvidenceSurface className="playground-customization-evidence" inset="none"><Grid.Root className="playground-customization-layout" columns={2} gap="0"><VStack gap="2"><SpecimenLabel>Customized</SpecimenLabel><PlaygroundCodeBlock aria-label="Context Menu customization code">{`style={{\n  "--brick-context-menu-content-radius": "0.25rem",\n  "--brick-context-menu-row-highlighted-background": "#dcfce7",\n  "--brick-context-menu-row-highlighted-foreground": "#166534",\n}}`}</PlaygroundCodeBlock></VStack><div className="menu-customization__preview playground-customization-preview"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="Customized report" tabIndex={0}><Text>Customized report</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="Customized report actions" style={customStyle}><ContextMenu.Item value="open"><ContextMenu.ItemLabel>Open report</ContextMenu.ItemLabel></ContextMenu.Item></ContextMenu.Content></ContextMenu.Root></div></Grid.Root></EvidenceSurface></Group></VStack></Scenario>
    <Scenario {...contextMenuScenarios[8]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="context-menu-stress"><Cell label="viewport edge"><div className="menu-phone"><FileContext label="Long localized document title" /></div></Cell><Cell label="RTL"><div className="menu-phone" dir="rtl"><ContextMenu.Root><ContextMenu.Trigger asChild><article className="menu-target" aria-label="تقرير المشروع" tabIndex={0}><Text>تقرير المشروع</Text></article></ContextMenu.Trigger><ContextMenu.Content ariaLabel="إجراءات التقرير"><ContextMenu.Item value="open"><ContextMenu.ItemLabel>فتح التقرير</ContextMenu.ItemLabel></ContextMenu.Item><ContextMenu.Sub><ContextMenu.SubTrigger value="move"><ContextMenu.ItemLabel>نقل إلى مجلد</ContextMenu.ItemLabel></ContextMenu.SubTrigger><ContextMenu.SubContent><ContextMenu.Item value="archive"><ContextMenu.ItemLabel>الأرشيف</ContextMenu.ItemLabel></ContextMenu.Item></ContextMenu.SubContent></ContextMenu.Sub></ContextMenu.Content></ContextMenu.Root></div></Cell></Grid.Root></Scenario>
  </VStack>;
}
