import { useState, type CSSProperties } from "react";
import { Badge, Button, Field, Fieldset, Form, Grid, OTPField, Text, VStack, type OTPFieldLayout, type OTPFieldShape, type OTPFieldSize, type OTPFieldVariant } from "@flowstack-ui/brick";
import { EvidenceSurface } from "../../shared/EvidenceSurface.js";import { Scenario,type ScenarioDefinition } from "../../shared/Scenario.js";import "../../shared/forms-evidence.playground.css";import "./otp-field.playground.css";
const variants:OTPFieldVariant[]=["outline","soft","underline"];const sizes:OTPFieldSize[]=["sm","md","lg"];const shapes:OTPFieldShape[]=["sharp","rounded"];const layouts:OTPFieldLayout[]=["separated","attached"];
const defs=[[1,"Overview","Canonical six-digit verification code composed with Field."],[2,"Variants","Outline, soft, and underline change cell paint only."],[3,"Sizes and shapes","Closed sizes and shapes retain equal cells."],[4,"Layouts","Separated and attached groups express spacing only."],[5,"Input behavior","Numeric filtering, paste, completion, masking, and localization remain Atom-owned."],[6,"States","Controlled, disabled, read-only, required, and invalid states remain distinct."],[7,"Form, Fieldset, and Field","Native submission, reset, validation, and inherited group state."],[8,"Appearance and customization","Light and dark scopes plus one documented token override."],[9,"Responsive and RTL","Narrow and right-to-left evidence remains contained."]] as const;export const otpFieldScenarios=defs.map(([number,title,description])=>({id:`otp-field.${number}`,number,title,description})) satisfies ScenarioDefinition[];
function Cells({length=6,separator=false}:{length?:number;separator?:boolean}){const first=separator?Math.ceil(length/2):length;return <>{<OTPField.Group>{Array.from({length:first},(_,i)=><OTPField.Input index={i} key={i}/>)}</OTPField.Group>}{separator?<><OTPField.Separator/><OTPField.Group>{Array.from({length:length-first},(_,i)=><OTPField.Input index={i+first} key={i+first}/>)}</OTPField.Group></>:null}</>};function Control(props:Omit<React.ComponentProps<typeof OTPField.Root>,"children">&{separator?:boolean}){const {separator,variant,shape,...root}=props;const recipe=variant==="underline"?{variant} as const:{variant,shape};return <OTPField.Root {...root} {...recipe}><Cells length={root.length} separator={separator}/></OTPField.Root>};function Labeled({id,children}:{id:string;children:React.ReactNode}){return <Field.Root id={id}><Field.Label>Verification code</Field.Label>{children}<Field.Description>Enter the code sent to your device.</Field.Description></Field.Root>}const custom={"--brick-otp-size":"3.25rem","--brick-otp-radius":"1rem"} as CSSProperties;
export function OTPFieldPage(){const [value,setValue]=useState("");const [status,setStatus]=useState("No form event yet");return <VStack className="forms-page specialized-field-page otp-field-page" data-component-page="otp-field">
<Scenario {...otpFieldScenarios[0]}><EvidenceSurface data-testid="otp-field-overview" inset="lg"><Labeled id="otp-overview"><Control length={6} name="code" separator/></Labeled></EvidenceSurface></Scenario>
<Scenario {...otpFieldScenarios[1]}><Grid.Root columns={3} className="forms-grid forms-grid--three" data-testid="otp-field-variants">{variants.map(v=><Labeled id={`otp-variant-${v}`} key={v}><Control length={4} variant={v}/></Labeled>)}</Grid.Root></Scenario>
<Scenario {...otpFieldScenarios[2]}><Grid.Root columns={3} className="forms-grid forms-grid--three" data-testid="otp-field-sizes">{sizes.map(s=><Labeled id={`otp-size-${s}`} key={s}><Control length={4} size={s}/></Labeled>)}{shapes.map(s=><Labeled id={`otp-shape-${s}`} key={s}><Control length={4} shape={s}/></Labeled>)}</Grid.Root></Scenario>
<Scenario {...otpFieldScenarios[3]}><Grid.Root columns={2} className="forms-grid forms-grid--two" data-testid="otp-field-layouts">{layouts.map(layout=><Labeled id={`otp-layout-${layout}`} key={layout}><Control layout={layout} length={4}/></Labeled>)}</Grid.Root></Scenario>
<Scenario {...otpFieldScenarios[4]}><Grid.Root columns={3} className="forms-grid forms-grid--three" data-testid="otp-field-behavior"><Labeled id="otp-numeric"><Control length={4}/></Labeled><Labeled id="otp-mask"><Control length={4} mask/></Labeled><Field.Root id="otp-localized"><Badge size="sm" variant="soft">Spanish localization</Badge><Field.Label>Código</Field.Label><Control getInputLabel={(i,l)=>`Dígito ${i+1} de ${l}`} length={4}/></Field.Root></Grid.Root></Scenario>
<Scenario {...otpFieldScenarios[5]}><Grid.Root columns={4} className="forms-grid forms-grid--four" data-testid="otp-field-states"><Labeled id="otp-controlled"><Control length={4} value={value} onValueChange={setValue}/><output><Text as="span">Value: {value||"empty"}</Text></output></Labeled><Labeled id="otp-disabled"><Control disabled length={4}/></Labeled><Labeled id="otp-readonly"><Control defaultValue="1234" length={4} readOnly/></Labeled><Field.Root id="otp-invalid" invalid required><Field.Label>Verification code</Field.Label><Control length={4}/><Field.Error>Enter all four digits.</Field.Error></Field.Root></Grid.Root></Scenario>
<Scenario {...otpFieldScenarios[6]}><EvidenceSurface data-testid="otp-field-form" inset="lg"><Form aria-label="Verification form" preventDefaultOnSubmit validationBehavior="inline" onReset={()=>setStatus("Form reset")} onSubmit={e=>setStatus(`Submitted: ${new FormData(e.currentTarget).get("verification")??"none"}`)}><Fieldset.Root required><Fieldset.Legend>Identity verification</Fieldset.Legend><Field.Root id="otp-form-code"><Field.Label>Security code</Field.Label><Control length={4} name="verification"/><Field.Error>Enter the security code.</Field.Error></Field.Root></Fieldset.Root><Button type="submit">Verify</Button><Button type="reset" variant="outline">Reset</Button><output><Text as="span">{status}</Text></output></Form></EvidenceSurface></Scenario>
<Scenario {...otpFieldScenarios[7]}><Grid.Root columns={3} className="forms-grid forms-grid--three" data-testid="otp-field-appearance"><EvidenceSurface data-brick-appearance="light" inset="md"><Badge size="sm" variant="soft">Light</Badge><Labeled id="otp-light"><Control length={4}/></Labeled></EvidenceSurface><EvidenceSurface data-brick-appearance="dark" inset="md"><Badge size="sm" variant="soft">Dark</Badge><Labeled id="otp-dark"><Control length={4}/></Labeled></EvidenceSurface><EvidenceSurface inset="md"><Badge size="sm" variant="soft">Customized</Badge><Text as="h3" variant="title-sm">Verification accent</Text><Text>Public variables scope one example.</Text><Labeled id="otp-custom"><Control length={4} style={custom}/></Labeled></EvidenceSurface></Grid.Root></Scenario>
<Scenario {...otpFieldScenarios[8]}><Grid.Root columns={2} className="forms-grid forms-grid--two specialized-stress" data-testid="otp-field-stress"><div><Badge size="sm" variant="soft">Narrow</Badge><Labeled id="otp-narrow"><Control length={6} separator/></Labeled></div><div dir="rtl"><Badge size="sm" variant="soft">RTL</Badge><Field.Root id="otp-rtl"><Field.Label>رمز التحقق</Field.Label><Control getInputLabel={(i,l)=>`الرقم ${i+1} من ${l}`} length={4}/></Field.Root></div></Grid.Root></Scenario></VStack>}
