"use client";
import { createContext, forwardRef, useContext, type ReactNode } from "react";
import { PasswordToggleField as AtomPassword, type PasswordToggleFieldIconProps as AtomIconProps, type PasswordToggleFieldInputProps as AtomInputProps, type PasswordToggleFieldRootProps as AtomRootProps, type PasswordToggleFieldToggleProps as AtomToggleProps } from "@flowstack-ui/atom/password-toggle-field";
export type PasswordToggleFieldVariant="outline"|"soft"|"underline"; export type PasswordToggleFieldSize="sm"|"md"|"lg"; export type PasswordToggleFieldShape="sharp"|"rounded"|"pill";
const VisualContext=createContext({fullWidth:true,shape:"rounded" as PasswordToggleFieldShape|undefined,size:"md" as PasswordToggleFieldSize,variant:"outline" as PasswordToggleFieldVariant});const cn=(a:string,b?:string)=>b?`${a} ${b}`:a;
type Shared=AtomRootProps&{className?:string;fullWidth?:boolean;size?:PasswordToggleFieldSize;"data-slot"?:string};export type PasswordToggleFieldRootProps=Shared&({variant?:"outline"|"soft";shape?:PasswordToggleFieldShape}|{variant:"underline";shape?:never});export type PasswordToggleFieldInputProps=AtomInputProps;export type PasswordToggleFieldToggleProps=Omit<AtomToggleProps,"children">&{children?:ReactNode};export type PasswordToggleFieldIconProps=Partial<Pick<AtomIconProps,"visible"|"hidden">>&Omit<AtomIconProps,"visible"|"hidden">;
function Eye({off=false}:{off?:boolean}){return <svg aria-hidden="true" className="brick-password-toggle-field-artwork" fill="none" viewBox="0 0 20 20"><path d="M2.5 10s2.75-4 7.5-4 7.5 4 7.5 4-2.75 4-7.5 4-7.5-4-7.5-4Z"/><circle cx="10" cy="10" r="2"/>{off?<path d="m3 3 14 14"/>:null}</svg>}
export function PasswordToggleFieldRoot({children,className,fullWidth = true,shape = "rounded",size = "md",variant = "outline","data-slot":dataSlot,...props}:PasswordToggleFieldRootProps){const v={fullWidth,shape:variant==="underline"?undefined:shape,size,variant};return <VisualContext.Provider value={v}><AtomPassword.Root {...props}><span className={cn("brick-password-toggle-field",className)} data-full-width={fullWidth?"":undefined} data-shape={v.shape} data-size={size} data-slot={dataSlot??"password-toggle-field"} data-variant={variant}>{children}</span></AtomPassword.Root></VisualContext.Provider>}
export const PasswordToggleFieldInput=forwardRef<HTMLInputElement,PasswordToggleFieldInputProps>(function PasswordToggleFieldInput({className,"data-slot":dataSlot,...props},ref){useContext(VisualContext);return <AtomPassword.Input {...props} className={cn("brick-password-toggle-field-input",className)} data-slot={dataSlot??"password-toggle-field-input"} ref={ref}/>});
export const PasswordToggleFieldToggle=forwardRef<HTMLButtonElement,PasswordToggleFieldToggleProps>(function PasswordToggleFieldToggle({children,className,"data-slot":dataSlot,...props},ref){return <AtomPassword.Toggle {...props} className={cn("brick-password-toggle-field-toggle",className)} data-slot={dataSlot??"password-toggle-field-toggle"} ref={ref}>{children??<PasswordToggleFieldIcon/>}</AtomPassword.Toggle>});
export const PasswordToggleFieldIcon=forwardRef<HTMLSpanElement,PasswordToggleFieldIconProps>(function PasswordToggleFieldIcon({hidden=<Eye/>,visible=<Eye off/>,className,"data-slot":dataSlot,...props},ref){return <AtomPassword.Icon {...props} className={cn("brick-password-toggle-field-icon",className)} data-slot={dataSlot??"password-toggle-field-icon"} hidden={hidden} ref={ref} visible={visible}/>});
export const PasswordToggleField={Root:PasswordToggleFieldRoot,Input:PasswordToggleFieldInput,Toggle:PasswordToggleFieldToggle,Icon:PasswordToggleFieldIcon} as const;
