import { useState, type CSSProperties, type ReactNode } from "react";
import { Button, DropdownMenu, Grid, Icon, IconButton, Text, VStack, type DropdownMenuSize } from "@flowstack-ui/brick";
import { Scenario, type ScenarioDefinition } from "../../shared/Scenario.js";
import { EvidenceSurface } from "../../shared/EvidenceSurface.js";
import { FormRenderedOutput as RenderedOutput } from "../../shared/FormEvidence.js";
import { PlaygroundCodeBlock } from "../../shared/PlaygroundCodeBlock.js";
import { SpecimenLabel } from "../../shared/SpecimenLabel.js";
import "../../styles/menu-evidence.css";
import "./dropdown-menu.playground.css";

const sizes: DropdownMenuSize[] = ["sm", "md", "lg"];
const customStyle = { "--brick-dropdown-menu-content-radius": "0.25rem", "--brick-dropdown-menu-row-highlighted-background": "#ede9fe", "--brick-dropdown-menu-row-highlighted-foreground": "#5b21b6" } as CSSProperties;

function Group({ children, description, title }: { children: ReactNode; description: string; title: string }) { return <VStack as="section" className="menu-evidence-group"><VStack className="menu-evidence-heading"><Text as="h3" variant="title-sm">{title}</Text><Text as="p" tone="secondary" variant="body-sm">{description}</Text></VStack>{children}</VStack>; }
function Cell({ children, label }: { children: ReactNode; label: string }) { return <EvidenceSurface className="menu-cell"><SpecimenLabel>{label}</SpecimenLabel><div className="menu-preview">{children}</div></EvidenceSurface>; }
function BasicMenu({ label = "Project actions", size = "md", children }: { label?: string; size?: DropdownMenuSize; children?: ReactNode }) { return <DropdownMenu.Root size={size}><DropdownMenu.Trigger asChild><Button tone="neutral" variant="outline">{label}</Button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content ariaLabel={label} sideOffset={6}>{children ?? <><DropdownMenu.Item value="rename"><DropdownMenu.ItemLabel>Rename project</DropdownMenu.ItemLabel><DropdownMenu.Shortcut>⌘R</DropdownMenu.Shortcut></DropdownMenu.Item><DropdownMenu.Item value="duplicate"><DropdownMenu.ItemLabel>Duplicate project</DropdownMenu.ItemLabel></DropdownMenu.Item></>}<DropdownMenu.Arrow /></DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>; }

export const dropdownMenuScenarios = [
  { id: "dropdown-menu.overview", number: 1, title: "Overview", description: "The default medium Dropdown Menu opens from a visible Button and presents temporary project commands on one neutral surface." },
  { id: "dropdown-menu.density", number: 2, title: "Density", description: "Small, medium, and large change only shared row typography, height, gaps, and surface padding." },
  { id: "dropdown-menu.anatomy", number: 3, title: "Item anatomy and grouping", navigationTitle: "Anatomy", description: "Labels, leading content, descriptions, shortcuts, groups, and separators occupy stable logical columns." },
  { id: "dropdown-menu.selection", number: 4, title: "Selection", description: "Checkbox, mixed, and radio items expose persistent application state with automatic indicators." },
  { id: "dropdown-menu.states", number: 5, title: "Content and states", navigationTitle: "States", description: "Neutral, highlighted, disabled, and danger commands keep identical default geometry." },
  { id: "dropdown-menu.submenus", number: 6, title: "Submenus", description: "Nested commands inherit density, positioning, focus, dismissal, and direction from Atom." },
  { id: "dropdown-menu.composition", number: 7, title: "Composition and output", navigationTitle: "Composition", description: "Button, Icon Button, render, and asChild hosts preserve one interactive element, roles, slots, classes, and refs." },
  { id: "dropdown-menu.appearance", number: 8, title: "Appearance and customization", navigationTitle: "Theme", description: "Light and dark scopes preserve defaults; one exact token override visibly changes only the documented surface recipe." },
  { id: "dropdown-menu.stress", number: 9, title: "Responsive, RTL, and preferences", navigationTitle: "Stress", description: "Long content, constrained height, RTL submenu direction, reduced motion, and forced colors remain readable and reachable." },
] as const satisfies readonly ScenarioDefinition[];

export function DropdownMenuPage() {
  const [updates, setUpdates] = useState(true); const [access, setAccess] = useState("team"); const [status, setStatus] = useState("No command selected.");
  return <VStack className="dropdown-menu-page menu-page" data-component-page="dropdown-menu" data-testid="dropdown-menu-workbench">
    <Scenario {...dropdownMenuScenarios[0]}><EvidenceSurface className="menu-overview" inset="lg" data-testid="dropdown-menu-overview"><BasicMenu /></EvidenceSurface></Scenario>
    <Scenario {...dropdownMenuScenarios[1]}><Grid.Root columns={3} className="menu-grid menu-grid--three" data-testid="dropdown-menu-density">{sizes.map((size) => <Cell key={size} label={size}><BasicMenu label="Project actions" size={size} /></Cell>)}</Grid.Root></Scenario>
    <Scenario {...dropdownMenuScenarios[2]}><EvidenceSurface className="menu-overview" inset="lg" data-testid="dropdown-menu-anatomy"><BasicMenu label="Inspect project menu"><DropdownMenu.Group><DropdownMenu.Label>Project</DropdownMenu.Label><DropdownMenu.Item value="rename"><DropdownMenu.Leading aria-hidden="true"><Icon data-testid="dropdown-leading-icon" size="xl"><svg fill="none" viewBox="0 0 16 16"><path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" /></svg></Icon></DropdownMenu.Leading><DropdownMenu.ItemLabel>Rename project</DropdownMenu.ItemLabel><DropdownMenu.Description>Change the visible workspace name.</DropdownMenu.Description><DropdownMenu.Shortcut>⌘R</DropdownMenu.Shortcut></DropdownMenu.Item><DropdownMenu.Item value="duplicate"><DropdownMenu.Leading aria-hidden="true">D</DropdownMenu.Leading><DropdownMenu.ItemLabel>Duplicate project</DropdownMenu.ItemLabel></DropdownMenu.Item></DropdownMenu.Group><DropdownMenu.Separator /><DropdownMenu.Group><DropdownMenu.Label>Workspace</DropdownMenu.Label><DropdownMenu.Item value="settings"><DropdownMenu.ItemLabel>Workspace settings</DropdownMenu.ItemLabel></DropdownMenu.Item></DropdownMenu.Group></BasicMenu></EvidenceSurface></Scenario>
    <Scenario {...dropdownMenuScenarios[3]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="dropdown-menu-selection"><Cell label="checkbox and mixed"><DropdownMenu.Root><DropdownMenu.Trigger asChild><Button tone="neutral" variant="outline">View options</Button></DropdownMenu.Trigger><DropdownMenu.Content ariaLabel="View options"><DropdownMenu.CheckboxItem checked={updates} onCheckedChange={(next) => setUpdates(next === true)} value="updates"><DropdownMenu.ItemIndicator /><DropdownMenu.ItemLabel>Email updates</DropdownMenu.ItemLabel></DropdownMenu.CheckboxItem><DropdownMenu.CheckboxItem checked="indeterminate" value="permissions"><DropdownMenu.ItemIndicator /><DropdownMenu.ItemLabel>Inherited permissions</DropdownMenu.ItemLabel></DropdownMenu.CheckboxItem></DropdownMenu.Content></DropdownMenu.Root></Cell><Cell label="radio"><DropdownMenu.Root><DropdownMenu.Trigger asChild><Button tone="neutral" variant="outline">Access level</Button></DropdownMenu.Trigger><DropdownMenu.Content ariaLabel="Access level"><DropdownMenu.RadioGroup value={access} onValueChange={setAccess}>{["private", "team", "public"].map((value) => <DropdownMenu.RadioItem key={value} value={value}><DropdownMenu.ItemIndicator /><DropdownMenu.ItemLabel>{value[0].toUpperCase() + value.slice(1)}</DropdownMenu.ItemLabel></DropdownMenu.RadioItem>)}</DropdownMenu.RadioGroup></DropdownMenu.Content></DropdownMenu.Root></Cell></Grid.Root></Scenario>
    <Scenario {...dropdownMenuScenarios[4]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="dropdown-menu-states"><Cell label="state comparison"><BasicMenu label="Command states"><DropdownMenu.Item onSelect={() => setStatus("Project opened.")} value="open"><DropdownMenu.ItemLabel>Open project</DropdownMenu.ItemLabel></DropdownMenu.Item><DropdownMenu.Item disabled value="locked"><DropdownMenu.ItemLabel>Locked command</DropdownMenu.ItemLabel></DropdownMenu.Item><DropdownMenu.Item onSelect={() => setStatus("Project deleted.")} tone="danger" value="delete"><DropdownMenu.ItemLabel>Delete project</DropdownMenu.ItemLabel></DropdownMenu.Item></BasicMenu><Text className="menu-status" role="status" tone="secondary" variant="body-sm">{status}</Text></Cell><Cell label="long content"><BasicMenu label="Localized commands"><DropdownMenu.Item value="long"><DropdownMenu.ItemLabel>ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 command</DropdownMenu.ItemLabel><DropdownMenu.Description>A longer localized explanation wraps without overlapping its trailing hint.</DropdownMenu.Description><DropdownMenu.Shortcut>Shift+⌘+P</DropdownMenu.Shortcut></DropdownMenu.Item></BasicMenu></Cell></Grid.Root></Scenario>
    <Scenario {...dropdownMenuScenarios[5]}><EvidenceSurface className="menu-overview" inset="lg" data-testid="dropdown-menu-submenus"><DropdownMenu.Root><DropdownMenu.Trigger asChild><Button tone="neutral" variant="outline">Move project</Button></DropdownMenu.Trigger><DropdownMenu.Content ariaLabel="Move project"><DropdownMenu.Item value="recent"><DropdownMenu.ItemLabel>Recent destination</DropdownMenu.ItemLabel></DropdownMenu.Item><DropdownMenu.Sub><DropdownMenu.SubTrigger value="workspace"><DropdownMenu.ItemLabel>Another workspace</DropdownMenu.ItemLabel></DropdownMenu.SubTrigger><DropdownMenu.SubContent ariaLabel="Workspace destinations"><DropdownMenu.Item value="design"><DropdownMenu.ItemLabel>Design system</DropdownMenu.ItemLabel></DropdownMenu.Item><DropdownMenu.Item value="research"><DropdownMenu.ItemLabel>Research archive</DropdownMenu.ItemLabel></DropdownMenu.Item></DropdownMenu.SubContent></DropdownMenu.Sub></DropdownMenu.Content></DropdownMenu.Root></EvidenceSurface></Scenario>
    <Scenario {...dropdownMenuScenarios[6]}><VStack className="menu-evidence-stack" data-testid="dropdown-menu-composition"><Group title="Trigger composition" description="Both triggers remain their native Brick controls; Dropdown Menu adds behavior without another button."><Grid.Root columns={2} className="menu-grid menu-grid--two"><Cell label="Button"><BasicMenu label="More actions" /></Cell><Cell label="Icon Button"><DropdownMenu.Root><DropdownMenu.Trigger asChild><IconButton aria-label="More project actions">•••</IconButton></DropdownMenu.Trigger><DropdownMenu.Content ariaLabel="More project actions"><DropdownMenu.Item value="rename"><DropdownMenu.ItemLabel>Rename project</DropdownMenu.ItemLabel></DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root></Cell></Grid.Root></Group><Group title="Rendered output" description="The composed trigger receives Atom and Brick attributes without an extra interactive wrapper."><RenderedOutput label="Dropdown Menu trigger HTML"><DropdownMenu.Root><DropdownMenu.Trigger asChild><button data-adapter="project-actions">Project actions</button></DropdownMenu.Trigger></DropdownMenu.Root></RenderedOutput></Group></VStack></Scenario>
    <Scenario {...dropdownMenuScenarios[7]}><VStack gap="5" data-testid="dropdown-menu-appearance"><Grid.Root columns={2} className="menu-grid menu-grid--two"><EvidenceSurface className="dropdown-menu-appearance-panel" data-brick-appearance="light"><SpecimenLabel>Light</SpecimenLabel><div className="dropdown-menu-appearance-preview"><BasicMenu label="Light project actions" /></div></EvidenceSurface><EvidenceSurface className="dropdown-menu-appearance-panel" data-brick-appearance="dark"><SpecimenLabel>Dark</SpecimenLabel><div className="dropdown-menu-appearance-preview"><BasicMenu label="Dark project actions" /></div></EvidenceSurface></Grid.Root><EvidenceSurface className="playground-customization-evidence" inset="none"><Grid.Root columns={2} gap="0" className="dropdown-menu-customization playground-customization-layout"><VStack gap="2"><SpecimenLabel>Customized</SpecimenLabel><Text as="h3" variant="title-sm">Dropdown Menu CSS properties</Text><Text tone="secondary" variant="body-sm">The squared popup and violet highlighted row use only the documented properties below.</Text><PlaygroundCodeBlock aria-label="Dropdown Menu customization code">{`--brick-dropdown-menu-content-radius: 0.25rem;\n--brick-dropdown-menu-row-highlighted-background: #ede9fe;\n--brick-dropdown-menu-row-highlighted-foreground: #5b21b6;`}</PlaygroundCodeBlock></VStack><div className="dropdown-menu-customization__preview"><DropdownMenu.Root><DropdownMenu.Trigger asChild><Button tone="neutral" variant="outline">Customized actions</Button></DropdownMenu.Trigger><DropdownMenu.Content ariaLabel="Customized actions" style={customStyle}><DropdownMenu.Item value="rename"><DropdownMenu.ItemLabel>Rename project</DropdownMenu.ItemLabel></DropdownMenu.Item></DropdownMenu.Content></DropdownMenu.Root></div></Grid.Root></EvidenceSurface></VStack></Scenario>
    <Scenario {...dropdownMenuScenarios[8]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="dropdown-menu-stress"><Cell label="constrained"><div className="menu-phone"><BasicMenu label="Constrained actions"><DropdownMenu.Item value="one"><DropdownMenu.ItemLabel>Very long project command that remains contained</DropdownMenu.ItemLabel></DropdownMenu.Item>{Array.from({ length: 8 }, (_, index) => <DropdownMenu.Item key={index} value={`item-${index}`}><DropdownMenu.ItemLabel>Reachable command {index + 1}</DropdownMenu.ItemLabel></DropdownMenu.Item>)}</BasicMenu></div></Cell><Cell label="RTL"><div className="menu-phone" dir="rtl"><DropdownMenu.Root><DropdownMenu.Trigger asChild><Button tone="neutral" variant="outline">إجراءات المشروع</Button></DropdownMenu.Trigger><DropdownMenu.Content ariaLabel="إجراءات المشروع"><DropdownMenu.Item value="rename"><DropdownMenu.ItemLabel>إعادة تسمية المشروع</DropdownMenu.ItemLabel></DropdownMenu.Item><DropdownMenu.Sub><DropdownMenu.SubTrigger value="move"><DropdownMenu.ItemLabel>نقل إلى مساحة عمل</DropdownMenu.ItemLabel></DropdownMenu.SubTrigger><DropdownMenu.SubContent><DropdownMenu.Item value="design"><DropdownMenu.ItemLabel>نظام التصميم</DropdownMenu.ItemLabel></DropdownMenu.Item></DropdownMenu.SubContent></DropdownMenu.Sub></DropdownMenu.Content></DropdownMenu.Root></div></Cell></Grid.Root></Scenario>
  </VStack>;
}
