export {
  Collapsible,
  CollapsibleContent,
  CollapsibleContentInner,
  CollapsibleIndicator,
  CollapsibleRoot,
  CollapsibleRootProvider,
  CollapsibleContext,
  useCollapsible,
  useCollapsibleContext,
  type UseCollapsibleOptions,
  type UseCollapsibleReturn,
  type CollapsibleRootProviderProps,
  type CollapsibleHighlight,
  CollapsibleTrigger,
  type CollapsibleContentInnerProps,
  type CollapsibleContentProps,
  type CollapsibleIndicatorProps,
  type CollapsibleRootProps,
  type CollapsibleSize,
  type CollapsibleTriggerProps,
  type CollapsibleVariant,
} from "./Collapsible.js";
