import { test, expect } from "../../evidence-test.js";
import AxeBuilder from "@axe-core/playwright";
test("DatePicker selects, restores focus and stays within viewport bounds", async ({ page }) => {
  await page.goto("/date-picker");
  const trigger = page.getByRole("button", { name: "Choose date", exact: true });
  await trigger.click();
  const popup = page.getByRole("dialog", { name: "Delivery calendar" });
  await expect(popup).toBeVisible();
  await expect(popup).toHaveCSS("opacity", "1");
  const box = await popup.boundingBox(); const viewport = page.viewportSize()!;
  expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.x + box!.width).toBeLessThanOrEqual(viewport.width);
  const results = await new AxeBuilder({ page }).include('[role="dialog"]').analyze();
  expect(results.violations.filter(item => ["serious", "critical"].includes(item.impact!))).toEqual([]);
  await popup.locator('button[data-value="2026-09-09"]').click();
  await expect(popup).toHaveCount(0); await expect(trigger).toBeFocused();
  await expect(page.locator('input[name="delivery"]')).toHaveValue("2026-09-09");
});
test("DatePicker Escape leaves the parent Dialog open", async ({ page }) => {
  await page.goto("/date-picker"); await page.getByRole("button", { name: "Schedule in dialog" }).click();
  const dialog = page.getByRole("dialog", { name: "Schedule delivery" });
  await dialog.getByRole("button", { name: "Choose date", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Delivery calendar" })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "Delivery calendar" })).toHaveCount(0);
  await expect(dialog).toBeVisible();
});
test("nested DatePicker accepts pointer selection above the parent Dialog", async ({ page }) => {
  await page.goto("/date-picker");
  await page.getByRole("button", { name: "Schedule in dialog" }).click();
  const parent = page.getByRole("dialog", { name: "Schedule delivery", exact: true });
  const trigger = parent.getByRole("button", { name: "Choose date", exact: true });
  await trigger.click();
  const popup = page.getByRole("dialog", { name: "Delivery calendar", exact: true });
  const day = popup.locator('button[data-value="2026-09-09"]');
  await day.click();
  await expect(popup).toHaveCount(0);
  await expect(parent).toBeVisible();
  await expect(parent.locator('input[name="delivery"]')).toHaveValue("2026-09-09");
  await expect(trigger).toBeFocused();
});
test("DatePicker range commits both endpoints before closing", async ({ page }) => {
  await page.goto("/date-picker"); await page.getByRole("button", { name: "Choose travel dates" }).click();
  const popup = page.getByRole("dialog", { name: "Travel calendar" });
  await popup.locator('button[data-value="2026-09-17"]').first().click();
  await expect(popup).toBeVisible();
  await popup.locator('button[data-value="2026-09-19"]').first().click();
  await expect(popup).toHaveCount(0);
  await expect(page.locator('input[name="travel[start]"]')).toHaveValue("2026-09-17");
  await expect(page.locator('input[name="travel[end]"]')).toHaveValue("2026-09-19");
});
test("controlled selection, constraints and custom trigger keep their public contracts", async ({ page }) => {
  await page.goto("/date-picker");
  const controlled = page.getByRole("region", { name: "Controlled selection", exact: true });
  await controlled.getByRole("button", { name: "Clear date" }).click();
  await expect(controlled.getByRole("status")).toHaveText("No appointment selected");
  await controlled.getByRole("button", { name: "Reset appointment" }).click();
  await expect(controlled.getByRole("status")).toHaveText("2026-09-05");
  await page.getByRole("button", { name: "Choose available delivery", exact: true }).click();
  const calendar = page.getByRole("dialog", { name: "available delivery calendar", exact: true });
  await expect(calendar.locator('button[data-value="2026-09-06"]')).toHaveAttribute("data-unavailable", "");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Choose disabled delivery", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Choose readOnly delivery", exact: true })).toBeDisabled();
  const custom = page.getByRole("button", { name: "Choose project date", exact: true });
  const box = await custom.boundingBox();
  expect(box!.width).toBeGreaterThan(box!.height * 2);
  await custom.click();
  const project = page.getByRole("dialog", { name: "Project calendar", exact: true });
  await expect(project.getByRole("combobox")).toHaveCount(2);
});
