// Generated by scripts/build-preview-registry.mjs from the canonical app module table.
import type { ComponentType } from "react";
import type { ScenarioDefinition } from "../shared/Scenario.js";
interface PreviewRegistration { load: () => Promise<{ Page: ComponentType; scenarios: readonly ScenarioDefinition[] }>; source: () => Promise<string>; height: number }
export const previewRegistry = {
  "accordion": {
    load: () => import("../components/accordion/AccordionPage.js").then(m => ({ Page: m.AccordionPage, scenarios: m.accordionScenarios })),
    source: () => import("../components/accordion/AccordionPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "action-bar": {
    load: () => import("../components/action-bar/ActionBarPage.js").then(m => ({ Page: m.ActionBarPage, scenarios: m.actionBarScenarios })),
    source: () => import("../components/action-bar/ActionBarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "alert": {
    load: () => import("../components/alert/AlertPage.js").then(m => ({ Page: m.AlertPage, scenarios: m.alertScenarios })),
    source: () => import("../components/alert/AlertPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "alert-dialog": {
    load: () => import("../components/alert-dialog/AlertDialogPage.js").then(m => ({ Page: m.AlertDialogPage, scenarios: m.alertDialogScenarios })),
    source: () => import("../components/alert-dialog/AlertDialogPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "app-bar": {
    load: () => import("../components/app-bar/AppBarPage.js").then(m => ({ Page: m.AppBarPage, scenarios: m.appBarScenarios })),
    source: () => import("../components/app-bar/AppBarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "appearance": {
    load: () => import("../components/appearance/AppearancePage.js").then(m => ({ Page: m.AppearancePage, scenarios: m.appearanceScenarios })),
    source: () => import("../components/appearance/AppearancePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "aspect-ratio": {
    load: () => import("../components/aspect-ratio/AspectRatioPage.js").then(m => ({ Page: m.AspectRatioPage, scenarios: m.aspectRatioScenarios })),
    source: () => import("../components/aspect-ratio/AspectRatioPage.tsx?raw").then(m => m.default),
    height: 640,
  },
  "avatar": {
    load: () => import("../components/avatar/AvatarPage.js").then(m => ({ Page: m.AvatarPage, scenarios: m.avatarScenarios })),
    source: () => import("../components/avatar/AvatarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "avatar-group": {
    load: () => import("../components/avatar-group/AvatarGroupPage.js").then(m => ({ Page: m.AvatarGroupPage, scenarios: m.avatarGroupScenarios })),
    source: () => import("../components/avatar-group/AvatarGroupPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "badge": {
    load: () => import("../components/badge/BadgePage.js").then(m => ({ Page: m.BadgePage, scenarios: m.badgeScenarios })),
    source: () => import("../components/badge/BadgePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "bleed": {
    load: () => import("../components/bleed/BleedPage.js").then(m => ({ Page: m.BleedPage, scenarios: m.bleedScenarios })),
    source: () => import("../components/bleed/BleedPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "blockquote": {
    load: () => import("../components/blockquote/BlockquotePage.js").then(m => ({ Page: m.BlockquotePage, scenarios: m.blockquoteScenarios })),
    source: () => import("../components/blockquote/BlockquotePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "bottom-navigation": {
    load: () => import("../components/bottom-navigation/BottomNavigationPage.js").then(m => ({ Page: m.BottomNavigationPage, scenarios: m.bottomNavigationScenarios })),
    source: () => import("../components/bottom-navigation/BottomNavigationPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "breadcrumb": {
    load: () => import("../components/breadcrumb/BreadcrumbPage.js").then(m => ({ Page: m.BreadcrumbPage, scenarios: m.breadcrumbScenarios })),
    source: () => import("../components/breadcrumb/BreadcrumbPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "button": {
    load: () => import("../components/button/ButtonPage.js").then(m => ({ Page: m.ButtonPage, scenarios: m.buttonScenarios })),
    source: () => import("../components/button/ButtonPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "calendar": {
    load: () => import("../components/calendar/CalendarPage.js").then(m => ({ Page: m.CalendarPage, scenarios: m.calendarScenarios })),
    source: () => import("../components/calendar/CalendarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "card": {
    load: () => import("../components/card/CardPage.js").then(m => ({ Page: m.CardPage, scenarios: m.cardScenarios })),
    source: () => import("../components/card/CardPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "carousel": {
    load: () => import("../components/carousel/CarouselPage.js").then(m => ({ Page: m.CarouselPage, scenarios: m.carouselScenarios })),
    source: () => import("../components/carousel/CarouselPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "center": {
    load: () => import("../components/center/CenterPage.js").then(m => ({ Page: m.CenterPage, scenarios: m.centerScenarios })),
    source: () => import("../components/center/CenterPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "checkbox": {
    load: () => import("../components/checkbox/CheckboxPage.js").then(m => ({ Page: m.CheckboxPage, scenarios: m.checkboxScenarios })),
    source: () => import("../components/checkbox/CheckboxPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "checkbox-group": {
    load: () => import("../components/checkbox-group/CheckboxGroupPage.js").then(m => ({ Page: m.CheckboxGroupPage, scenarios: m.checkboxGroupScenarios })),
    source: () => import("../components/checkbox-group/CheckboxGroupPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "checkmark": {
    load: () => import("../components/checkmark/CheckmarkPage.js").then(m => ({ Page: m.CheckmarkPage, scenarios: m.checkmarkScenarios })),
    source: () => import("../components/checkmark/CheckmarkPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "chip": {
    load: () => import("../components/chip/ChipPage.js").then(m => ({ Page: m.ChipPage, scenarios: m.chipScenarios })),
    source: () => import("../components/chip/ChipPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "close-button": {
    load: () => import("../components/close-button/CloseButtonPage.js").then(m => ({ Page: m.CloseButtonPage, scenarios: m.closeButtonScenarios })),
    source: () => import("../components/close-button/CloseButtonPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "code": {
    load: () => import("../components/code/CodePage.js").then(m => ({ Page: m.CodePage, scenarios: m.codeScenarios })),
    source: () => import("../components/code/CodePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "code-block": {
    load: () => import("../components/code-block/CodeBlockPage.js").then(m => ({ Page: m.CodeBlockPage, scenarios: m.codeBlockScenarios })),
    source: () => import("../components/code-block/CodeBlockPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "collapsible": {
    load: () => import("../components/collapsible/CollapsiblePage.js").then(m => ({ Page: m.CollapsiblePage, scenarios: m.collapsibleScenarios })),
    source: () => import("../components/collapsible/CollapsiblePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "color-picker": {
    load: () => import("../components/color-picker/ColorPickerPage.js").then(m => ({ Page: m.ColorPickerPage, scenarios: m.colorPickerScenarios })),
    source: () => import("../components/color-picker/ColorPickerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "color-swatch": {
    load: () => import("../components/color-swatch/ColorSwatchPage.js").then(m => ({ Page: m.ColorSwatchPage, scenarios: m.colorSwatchScenarios })),
    source: () => import("../components/color-swatch/ColorSwatchPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "combobox": {
    load: () => import("../components/combobox/ComboboxPage.js").then(m => ({ Page: m.ComboboxPage, scenarios: m.comboboxScenarios })),
    source: () => import("../components/combobox/ComboboxPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "container": {
    load: () => import("../components/container/ContainerPage.js").then(m => ({ Page: m.ContainerPage, scenarios: m.containerScenarios })),
    source: () => import("../components/container/ContainerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "context-menu": {
    load: () => import("../components/context-menu/ContextMenuPage.js").then(m => ({ Page: m.ContextMenuPage, scenarios: m.contextMenuScenarios })),
    source: () => import("../components/context-menu/ContextMenuPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "data-grid": {
    load: () => import("../components/data-grid/DataGridPage.js").then(m => ({ Page: m.DataGridPage, scenarios: m.dataGridScenarios })),
    source: () => import("../components/data-grid/DataGridPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "data-list": {
    load: () => import("../components/data-list/DataListPage.js").then(m => ({ Page: m.DataListPage, scenarios: m.dataListScenarios })),
    source: () => import("../components/data-list/DataListPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "date-input": {
    load: () => import("../components/date-input/DateInputPage.js").then(m => ({ Page: m.DateInputPage, scenarios: m.dateInputScenarios })),
    source: () => import("../components/date-input/DateInputPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "date-picker": {
    load: () => import("../components/date-picker/DatePickerPage.js").then(m => ({ Page: m.DatePickerPage, scenarios: m.datePickerScenarios })),
    source: () => import("../components/date-picker/DatePickerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "dialog": {
    load: () => import("../components/dialog/DialogPage.js").then(m => ({ Page: m.DialogPage, scenarios: m.dialogScenarios })),
    source: () => import("../components/dialog/DialogPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "divider": {
    load: () => import("../components/divider/DividerPage.js").then(m => ({ Page: m.DividerPage, scenarios: m.dividerScenarios })),
    source: () => import("../components/divider/DividerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "download-trigger": {
    load: () => import("../components/download-trigger/DownloadTriggerPage.js").then(m => ({ Page: m.DownloadTriggerPage, scenarios: m.downloadTriggerScenarios })),
    source: () => import("../components/download-trigger/DownloadTriggerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "drawer": {
    load: () => import("../components/drawer/DrawerPage.js").then(m => ({ Page: m.DrawerPage, scenarios: m.drawerScenarios })),
    source: () => import("../components/drawer/DrawerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "dropdown-menu": {
    load: () => import("../components/dropdown-menu/DropdownMenuPage.js").then(m => ({ Page: m.DropdownMenuPage, scenarios: m.dropdownMenuScenarios })),
    source: () => import("../components/dropdown-menu/DropdownMenuPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "editable": {
    load: () => import("../components/editable/EditablePage.js").then(m => ({ Page: m.EditablePage, scenarios: m.editableScenarios })),
    source: () => import("../components/editable/EditablePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "em": {
    load: () => import("../components/em/EmPage.js").then(m => ({ Page: m.EmPage, scenarios: m.emScenarios })),
    source: () => import("../components/em/EmPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "empty-state": {
    load: () => import("../components/empty-state/EmptyStatePage.js").then(m => ({ Page: m.EmptyStatePage, scenarios: m.emptyStateScenarios })),
    source: () => import("../components/empty-state/EmptyStatePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "feed": {
    load: () => import("../components/feed/FeedPage.js").then(m => ({ Page: m.FeedPage, scenarios: m.feedScenarios })),
    source: () => import("../components/feed/FeedPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "field": {
    load: () => import("../components/field/FieldPage.js").then(m => ({ Page: m.FieldPage, scenarios: m.fieldScenarios })),
    source: () => import("../components/field/FieldPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "fieldset": {
    load: () => import("../components/fieldset/FieldsetPage.js").then(m => ({ Page: m.FieldsetPage, scenarios: m.fieldsetScenarios })),
    source: () => import("../components/fieldset/FieldsetPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "file-upload": {
    load: () => import("../components/file-upload/FileUploadPage.js").then(m => ({ Page: m.FileUploadPage, scenarios: m.fileUploadScenarios })),
    source: () => import("../components/file-upload/FileUploadPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "floating-panel": {
    load: () => import("../components/floating-panel/FloatingPanelPage.js").then(m => ({ Page: m.FloatingPanelPage, scenarios: m.floatingPanelScenarios })),
    source: () => import("../components/floating-panel/FloatingPanelPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "for": {
    load: () => import("../components/for/ForPage.js").then(m => ({ Page: m.ForPage, scenarios: m.forScenarios })),
    source: () => import("../components/for/ForPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "form": {
    load: () => import("../components/form/FormPage.js").then(m => ({ Page: m.FormPage, scenarios: m.formScenarios })),
    source: () => import("../components/form/FormPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "format-byte": {
    load: () => import("../components/format-byte/FormatBytePage.js").then(m => ({ Page: m.FormatBytePage, scenarios: m.formatByteScenarios })),
    source: () => import("../components/format-byte/FormatBytePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "format-number": {
    load: () => import("../components/format-number/FormatNumberPage.js").then(m => ({ Page: m.FormatNumberPage, scenarios: m.formatNumberScenarios })),
    source: () => import("../components/format-number/FormatNumberPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "frame": {
    load: () => import("../components/frame/FramePage.js").then(m => ({ Page: m.FramePage, scenarios: m.frameScenarios })),
    source: () => import("../components/frame/FramePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "grid": {
    load: () => import("../components/grid/GridPage.js").then(m => ({ Page: m.GridPage, scenarios: m.gridScenarios })),
    source: () => import("../components/grid/GridPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "group": {
    load: () => import("../components/group/GroupPage.js").then(m => ({ Page: m.GroupPage, scenarios: m.groupScenarios })),
    source: () => import("../components/group/GroupPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "hide": {
    load: () => import("../components/hide/HidePage.js").then(m => ({ Page: m.HidePage, scenarios: m.hideScenarios })),
    source: () => import("../components/hide/HidePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "highlight": {
    load: () => import("../components/highlight/HighlightPage.js").then(m => ({ Page: m.HighlightPage, scenarios: m.highlightScenarios })),
    source: () => import("../components/highlight/HighlightPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "hover-card": {
    load: () => import("../components/hover-card/HoverCardPage.js").then(m => ({ Page: m.HoverCardPage, scenarios: m.hoverCardScenarios })),
    source: () => import("../components/hover-card/HoverCardPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "icon": {
    load: () => import("../components/icon/IconPage.js").then(m => ({ Page: m.IconPage, scenarios: m.iconScenarios })),
    source: () => import("../components/icon/IconPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "icon-button": {
    load: () => import("../components/icon-button/IconButtonPage.js").then(m => ({ Page: m.IconButtonPage, scenarios: m.iconButtonScenarios })),
    source: () => import("../components/icon-button/IconButtonPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "image": {
    load: () => import("../components/image/ImagePage.js").then(m => ({ Page: m.ImagePage, scenarios: m.imageScenarios })),
    source: () => import("../components/image/ImagePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "input": {
    load: () => import("../components/input/InputPage.js").then(m => ({ Page: m.InputPage, scenarios: m.inputScenarios })),
    source: () => import("../components/input/InputPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "kbd": {
    load: () => import("../components/kbd/KbdPage.js").then(m => ({ Page: m.KbdPage, scenarios: m.kbdScenarios })),
    source: () => import("../components/kbd/KbdPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "link": {
    load: () => import("../components/link/LinkPage.js").then(m => ({ Page: m.LinkPage, scenarios: m.linkScenarios })),
    source: () => import("../components/link/LinkPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "link-box": {
    load: () => import("../components/link-box/LinkBoxPage.js").then(m => ({ Page: m.LinkBoxPage, scenarios: m.linkBoxScenarios })),
    source: () => import("../components/link-box/LinkBoxPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "list": {
    load: () => import("../components/list/ListPage.js").then(m => ({ Page: m.ListPage, scenarios: m.listScenarios })),
    source: () => import("../components/list/ListPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "locale-provider": {
    load: () => import("../components/locale-provider/LocaleProviderPage.js").then(m => ({ Page: m.LocaleProviderPage, scenarios: m.localeProviderScenarios })),
    source: () => import("../components/locale-provider/LocaleProviderPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "mark": {
    load: () => import("../components/mark/MarkPage.js").then(m => ({ Page: m.MarkPage, scenarios: m.markScenarios })),
    source: () => import("../components/mark/MarkPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "marquee": {
    load: () => import("../components/marquee/MarqueePage.js").then(m => ({ Page: m.MarqueePage, scenarios: m.marqueeScenarios })),
    source: () => import("../components/marquee/MarqueePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "menubar": {
    load: () => import("../components/menubar/MenubarPage.js").then(m => ({ Page: m.MenubarPage, scenarios: m.menubarScenarios })),
    source: () => import("../components/menubar/MenubarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "multi-select": {
    load: () => import("../components/multi-select/MultiSelectPage.js").then(m => ({ Page: m.MultiSelectPage, scenarios: m.multiSelectScenarios })),
    source: () => import("../components/multi-select/MultiSelectPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "native-select": {
    load: () => import("../components/native-select/NativeSelectPage.js").then(m => ({ Page: m.NativeSelectPage, scenarios: m.nativeSelectScenarios })),
    source: () => import("../components/native-select/NativeSelectPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "nav-list": {
    load: () => import("../components/nav-list/NavListPage.js").then(m => ({ Page: m.NavListPage, scenarios: m.navListScenarios })),
    source: () => import("../components/nav-list/NavListPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "navigation-menu": {
    load: () => import("../components/navigation-menu/NavigationMenuPage.js").then(m => ({ Page: m.NavigationMenuPage, scenarios: m.navigationMenuScenarios })),
    source: () => import("../components/navigation-menu/NavigationMenuPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "notification-badge": {
    load: () => import("../components/notification-badge/NotificationBadgePage.js").then(m => ({ Page: m.NotificationBadgePage, scenarios: m.notificationBadgeScenarios })),
    source: () => import("../components/notification-badge/NotificationBadgePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "number-input": {
    load: () => import("../components/number-input/NumberInputPage.js").then(m => ({ Page: m.NumberInputPage, scenarios: m.numberInputScenarios })),
    source: () => import("../components/number-input/NumberInputPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "overlay-manager": {
    load: () => import("../components/overlay-manager/OverlayManagerPage.js").then(m => ({ Page: m.OverlayManagerPage, scenarios: m.overlayManagerScenarios })),
    source: () => import("../components/overlay-manager/OverlayManagerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "pagination": {
    load: () => import("../components/pagination/PaginationPage.js").then(m => ({ Page: m.PaginationPage, scenarios: m.paginationScenarios })),
    source: () => import("../components/pagination/PaginationPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "password-toggle-field": {
    load: () => import("../components/password-toggle-field/PasswordToggleFieldPage.js").then(m => ({ Page: m.PasswordToggleFieldPage, scenarios: m.passwordToggleFieldScenarios })),
    source: () => import("../components/password-toggle-field/PasswordToggleFieldPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "pin-input": {
    load: () => import("../components/pin-input/PinInputPage.js").then(m => ({ Page: m.PinInputPage, scenarios: m.pinInputScenarios })),
    source: () => import("../components/pin-input/PinInputPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "popover": {
    load: () => import("../components/popover/PopoverPage.js").then(m => ({ Page: m.PopoverPage, scenarios: m.popoverScenarios })),
    source: () => import("../components/popover/PopoverPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "progress": {
    load: () => import("../components/progress/ProgressPage.js").then(m => ({ Page: m.ProgressPage, scenarios: m.progressScenarios })),
    source: () => import("../components/progress/ProgressPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "progress-circle": {
    load: () => import("../components/progress-circle/ProgressCirclePage.js").then(m => ({ Page: m.ProgressCirclePage, scenarios: m.progressCircleScenarios })),
    source: () => import("../components/progress-circle/ProgressCirclePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "prose": {
    load: () => import("../components/prose/ProsePage.js").then(m => ({ Page: m.ProsePage, scenarios: m.proseScenarios })),
    source: () => import("../components/prose/ProsePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "qr-code": {
    load: () => import("../components/qr-code/QrCodePage.js").then(m => ({ Page: m.QrCodePage, scenarios: m.qrCodeScenarios })),
    source: () => import("../components/qr-code/QrCodePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "radio-card": {
    load: () => import("../components/radio-card/RadioCardPage.js").then(m => ({ Page: m.RadioCardPage, scenarios: m.radioCardScenarios })),
    source: () => import("../components/radio-card/RadioCardPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "radio-group": {
    load: () => import("../components/radio-group/RadioGroupPage.js").then(m => ({ Page: m.RadioGroupPage, scenarios: m.radioGroupScenarios })),
    source: () => import("../components/radio-group/RadioGroupPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "radiomark": {
    load: () => import("../components/radiomark/RadiomarkPage.js").then(m => ({ Page: m.RadiomarkPage, scenarios: m.radiomarkScenarios })),
    source: () => import("../components/radiomark/RadiomarkPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "rating": {
    load: () => import("../components/rating/RatingPage.js").then(m => ({ Page: m.RatingPage, scenarios: m.ratingScenarios })),
    source: () => import("../components/rating/RatingPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "reorderable-list": {
    load: () => import("../components/reorderable-list/ReorderableListPage.js").then(m => ({ Page: m.ReorderableListPage, scenarios: m.reorderableListScenarios })),
    source: () => import("../components/reorderable-list/ReorderableListPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "scroll-area": {
    load: () => import("../components/scroll-area/ScrollAreaPage.js").then(m => ({ Page: m.ScrollAreaPage, scenarios: m.scrollAreaScenarios })),
    source: () => import("../components/scroll-area/ScrollAreaPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "section": {
    load: () => import("../components/section/SectionPage.js").then(m => ({ Page: m.SectionPage, scenarios: m.sectionScenarios })),
    source: () => import("../components/section/SectionPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "segment-group": {
    load: () => import("../components/segment-group/SegmentGroupPage.js").then(m => ({ Page: m.SegmentGroupPage, scenarios: m.segmentGroupScenarios })),
    source: () => import("../components/segment-group/SegmentGroupPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "select": {
    load: () => import("../components/select/SelectPage.js").then(m => ({ Page: m.SelectPage, scenarios: m.selectScenarios })),
    source: () => import("../components/select/SelectPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "show": {
    load: () => import("../components/show/ShowPage.js").then(m => ({ Page: m.ShowPage, scenarios: m.showScenarios })),
    source: () => import("../components/show/ShowPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "sidebar": {
    load: () => import("../components/sidebar/SidebarPage.js").then(m => ({ Page: m.SidebarPage, scenarios: m.sidebarScenarios })),
    source: () => import("../components/sidebar/SidebarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "skeleton": {
    load: () => import("../components/skeleton/SkeletonPage.js").then(m => ({ Page: m.SkeletonPage, scenarios: m.skeletonScenarios })),
    source: () => import("../components/skeleton/SkeletonPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "skip-link": {
    load: () => import("../components/skip-link/SkipLinkPage.js").then(m => ({ Page: m.SkipLinkPage, scenarios: m.skipLinkScenarios })),
    source: () => import("../components/skip-link/SkipLinkPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "slider": {
    load: () => import("../components/slider/SliderPage.js").then(m => ({ Page: m.SliderPage, scenarios: m.sliderScenarios })),
    source: () => import("../components/slider/SliderPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "spinner": {
    load: () => import("../components/spinner/SpinnerPage.js").then(m => ({ Page: m.SpinnerPage, scenarios: m.spinnerScenarios })),
    source: () => import("../components/spinner/SpinnerPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "splitter": {
    load: () => import("../components/splitter/SplitterPage.js").then(m => ({ Page: m.SplitterPage, scenarios: m.splitterScenarios })),
    source: () => import("../components/splitter/SplitterPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "stack": {
    load: () => import("../components/stack/StackPage.js").then(m => ({ Page: m.StackPage, scenarios: m.stackScenarios })),
    source: () => import("../components/stack/StackPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "stat": {
    load: () => import("../components/stat/StatPage.js").then(m => ({ Page: m.StatPage, scenarios: m.statScenarios })),
    source: () => import("../components/stat/StatPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "status": {
    load: () => import("../components/status/StatusPage.js").then(m => ({ Page: m.StatusPage, scenarios: m.statusScenarios })),
    source: () => import("../components/status/StatusPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "steps": {
    load: () => import("../components/steps/StepsPage.js").then(m => ({ Page: m.StepsPage, scenarios: m.stepsScenarios })),
    source: () => import("../components/steps/StepsPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "surface": {
    load: () => import("../components/surface/SurfacePage.js").then(m => ({ Page: m.SurfacePage, scenarios: m.surfaceScenarios })),
    source: () => import("../components/surface/SurfacePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "swipeable-item": {
    load: () => import("../components/swipeable-item/SwipeableItemPage.js").then(m => ({ Page: m.SwipeableItemPage, scenarios: m.swipeableItemScenarios })),
    source: () => import("../components/swipeable-item/SwipeableItemPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "switch": {
    load: () => import("../components/switch/SwitchPage.js").then(m => ({ Page: m.SwitchPage, scenarios: m.switchScenarios })),
    source: () => import("../components/switch/SwitchPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "table": {
    load: () => import("../components/table/TablePage.js").then(m => ({ Page: m.TablePage, scenarios: m.tableScenarios })),
    source: () => import("../components/table/TablePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "table-of-contents": {
    load: () => import("../components/table-of-contents/TableOfContentsPage.js").then(m => ({ Page: m.TableOfContentsPage, scenarios: m.tableOfContentsScenarios })),
    source: () => import("../components/table-of-contents/TableOfContentsPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "tabs": {
    load: () => import("../components/tabs/TabsPage.js").then(m => ({ Page: m.TabsPage, scenarios: m.tabsScenarios })),
    source: () => import("../components/tabs/TabsPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "tags-input": {
    load: () => import("../components/tags-input/TagsInputPage.js").then(m => ({ Page: m.TagsInputPage, scenarios: m.tagsInputScenarios })),
    source: () => import("../components/tags-input/TagsInputPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "text": {
    load: () => import("../components/text/TextPage.js").then(m => ({ Page: m.TextPage, scenarios: m.textScenarios })),
    source: () => import("../components/text/TextPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "textarea": {
    load: () => import("../components/textarea/TextareaPage.js").then(m => ({ Page: m.TextareaPage, scenarios: m.textareaScenarios })),
    source: () => import("../components/textarea/TextareaPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "timeline": {
    load: () => import("../components/timeline/TimelinePage.js").then(m => ({ Page: m.TimelinePage, scenarios: m.timelineScenarios })),
    source: () => import("../components/timeline/TimelinePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "toast": {
    load: () => import("../components/toast/ToastPage.js").then(m => ({ Page: m.ToastPage, scenarios: m.toastScenarios })),
    source: () => import("../components/toast/ToastPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "toggle": {
    load: () => import("../components/toggle/TogglePage.js").then(m => ({ Page: m.TogglePage, scenarios: m.toggleScenarios })),
    source: () => import("../components/toggle/TogglePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "toggle-group": {
    load: () => import("../components/toggle-group/ToggleGroupPage.js").then(m => ({ Page: m.ToggleGroupPage, scenarios: m.toggleGroupScenarios })),
    source: () => import("../components/toggle-group/ToggleGroupPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "toolbar": {
    load: () => import("../components/toolbar/ToolbarPage.js").then(m => ({ Page: m.ToolbarPage, scenarios: m.toolbarScenarios })),
    source: () => import("../components/toolbar/ToolbarPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "tooltip": {
    load: () => import("../components/tooltip/TooltipPage.js").then(m => ({ Page: m.TooltipPage, scenarios: m.tooltipScenarios })),
    source: () => import("../components/tooltip/TooltipPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "tree": {
    load: () => import("../components/tree/TreePage.js").then(m => ({ Page: m.TreePage, scenarios: m.treeScenarios })),
    source: () => import("../components/tree/TreePage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "tree-grid": {
    load: () => import("../components/tree-grid/TreeGridPage.js").then(m => ({ Page: m.TreeGridPage, scenarios: m.treeGridScenarios })),
    source: () => import("../components/tree-grid/TreeGridPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "visually-hidden": {
    load: () => import("../components/visually-hidden/VisuallyHiddenPage.js").then(m => ({ Page: m.VisuallyHiddenPage, scenarios: m.visuallyHiddenScenarios })),
    source: () => import("../components/visually-hidden/VisuallyHiddenPage.tsx?raw").then(m => m.default),
    height: 720,
  },
  "z-stack": {
    load: () => import("../components/z-stack/ZStackPage.js").then(m => ({ Page: m.ZStackPage, scenarios: m.zStackScenarios })),
    source: () => import("../components/z-stack/ZStackPage.tsx?raw").then(m => m.default),
    height: 720,
  },
} satisfies Record<string, PreviewRegistration>;
export type PreviewComponent = keyof typeof previewRegistry;
export function isPreviewComponent(value: string): value is PreviewComponent { return Object.prototype.hasOwnProperty.call(previewRegistry, value); }
