import { useState, type CSSProperties, type ReactNode } from "react";
import { Code, Grid, Menubar, Text, VStack, type MenubarSize } from "@flowstack-ui/brick";
import { Scenario, type ScenarioDefinition } from "../../shared/Scenario.js";
import { EvidenceSurface } from "../../shared/EvidenceSurface.js";
import { FormRenderedOutput as RenderedOutput } from "../../shared/FormEvidence.js";
import { PlaygroundCodeBlock } from "../../shared/PlaygroundCodeBlock.js";
import { SpecimenLabel } from "../../shared/SpecimenLabel.js";
import "../../styles/menu-evidence.css";

const sizes: MenubarSize[] = ["sm", "md", "lg"];
const customStyle = { "--brick-menubar-background": "#f5f3ff", "--brick-menubar-border": "#8b5cf6", "--brick-menubar-trigger-open-background": "#ddd6fe", "--brick-menubar-trigger-open-foreground": "#5b21b6" } as CSSProperties;
function Group({ children, description, title }: { children: ReactNode; description: string; title: string }) { return <VStack as="section" className="menu-evidence-group"><VStack className="menu-evidence-heading"><Text as="h3" variant="title-sm">{title}</Text><Text as="p" tone="secondary" variant="body-sm">{description}</Text></VStack>{children}</VStack>; }
function Cell({ children, label }: { children: ReactNode; label: string }) { return <EvidenceSurface className="menu-cell" level="canvas"><SpecimenLabel>{label}</SpecimenLabel><div className="menu-preview">{children}</div></EvidenceSurface>; }
function EditorMenubar({ defaultValue, orientation = "horizontal", size = "md", style }: { defaultValue?: string; orientation?: "horizontal" | "vertical"; size?: MenubarSize; style?: CSSProperties }) { return <Menubar.Root aria-label="Editor commands" defaultValue={defaultValue} orientation={orientation} size={size} style={style}><Menubar.Menu value="file"><Menubar.Trigger>File</Menubar.Trigger><Menubar.Portal><Menubar.Content ariaLabel="File commands"><Menubar.Item value="new"><Menubar.ItemLabel>New file</Menubar.ItemLabel><Menubar.Shortcut>⌘N</Menubar.Shortcut></Menubar.Item><Menubar.Item value="open"><Menubar.ItemLabel>Open file</Menubar.ItemLabel><Menubar.Shortcut>⌘O</Menubar.Shortcut></Menubar.Item></Menubar.Content></Menubar.Portal></Menubar.Menu><Menubar.Menu value="edit"><Menubar.Trigger>Edit</Menubar.Trigger><Menubar.Content ariaLabel="Edit commands"><Menubar.Item value="undo"><Menubar.ItemLabel>Undo</Menubar.ItemLabel><Menubar.Shortcut>⌘Z</Menubar.Shortcut></Menubar.Item><Menubar.Item value="redo"><Menubar.ItemLabel>Redo</Menubar.ItemLabel></Menubar.Item></Menubar.Content></Menubar.Menu><Menubar.Menu value="view"><Menubar.Trigger>View</Menubar.Trigger><Menubar.Content ariaLabel="View commands"><Menubar.Item value="zoom"><Menubar.ItemLabel>Actual size</Menubar.ItemLabel></Menubar.Item></Menubar.Content></Menubar.Menu></Menubar.Root>; }

export const menubarScenarios = [
  { id: "menubar.overview", number: 1, title: "Overview", description: "The default medium horizontal Menubar exposes persistent File, Edit, and View application-command categories." },
  { id: "menubar.orientation", number: 2, title: "Root orientation", navigationTitle: "Orientation", description: "Horizontal and vertical roots preserve command semantics while changing only layout and directional keyboard movement." },
  { id: "menubar.density", number: 3, title: "Density", description: "Small, medium, and large change top-level trigger and inherited popup density together." },
  { id: "menubar.triggers", number: 4, title: "Trigger states", navigationTitle: "Triggers", description: "Idle, focused, open, and disabled command categories remain visually distinct without changing geometry." },
  { id: "menubar.anatomy", number: 5, title: "Item anatomy and grouping", navigationTitle: "Anatomy", description: "Popup labels, leading content, descriptions, shortcuts, separators, disabled and danger items use the shared action-menu recipe." },
  { id: "menubar.selection", number: 6, title: "Selection and submenus", navigationTitle: "Selection", description: "Checkbox, mixed, radio, and nested commands inherit Menubar density and active-menu coordination." },
  { id: "menubar.composition", number: 7, title: "Composition and output", navigationTitle: "Composition", description: "Root and Trigger composition preserve the menubar relationship, roles, state, native props, classes, slots, and refs." },
  { id: "menubar.appearance", number: 8, title: "Appearance and customization", navigationTitle: "Theme", description: "The neutral command strip and popup remain coherent in scoped appearances and exact public-token overrides." },
  { id: "menubar.stress", number: 9, title: "Responsive, RTL, and preferences", navigationTitle: "Stress", description: "Narrow application regions use explicit overflow ownership; RTL, reduced motion, forced colors, and touch remain usable without automatic collapse." },
] as const satisfies readonly ScenarioDefinition[];

export function MenubarPage() {
  const [lineNumbers, setLineNumbers] = useState(true); const [theme, setTheme] = useState("system");
  return <VStack className="menu-page" data-component-page="menubar" data-testid="menubar-workbench">
    <Scenario {...menubarScenarios[0]}><EvidenceSurface className="menu-overview" inset="lg" data-testid="menubar-overview"><EditorMenubar defaultValue="file" /></EvidenceSurface></Scenario>
    <Scenario {...menubarScenarios[1]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="menubar-orientation"><Cell label="horizontal"><EditorMenubar /></Cell><Cell label="vertical"><EditorMenubar orientation="vertical" /></Cell></Grid.Root></Scenario>
    <Scenario {...menubarScenarios[2]}><Grid.Root columns={3} className="menu-grid menu-grid--three" data-testid="menubar-density">{sizes.map((size) => <Cell key={size} label={size}><EditorMenubar size={size} /></Cell>)}</Grid.Root></Scenario>
    <Scenario {...menubarScenarios[3]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="menubar-triggers"><Cell label="open"><EditorMenubar defaultValue="file" /></Cell><Cell label="disabled"><Menubar.Root aria-label="Unavailable editor commands"><Menubar.Menu value="file"><Menubar.Trigger disabled>File</Menubar.Trigger><Menubar.Content><Menubar.Item value="new">New file</Menubar.Item></Menubar.Content></Menubar.Menu><Menubar.Menu value="edit"><Menubar.Trigger>Edit</Menubar.Trigger><Menubar.Content><Menubar.Item value="undo">Undo</Menubar.Item></Menubar.Content></Menubar.Menu></Menubar.Root></Cell></Grid.Root></Scenario>
    <Scenario {...menubarScenarios[4]}><EvidenceSurface className="menu-overview" inset="lg" data-testid="menubar-anatomy"><Menubar.Root aria-label="Document commands" defaultValue="document"><Menubar.Menu value="document"><Menubar.Trigger>Document</Menubar.Trigger><Menubar.Content ariaLabel="Document commands"><Menubar.Group><Menubar.Label>Document</Menubar.Label><Menubar.Item value="rename"><Menubar.Leading aria-hidden="true">R</Menubar.Leading><Menubar.ItemLabel>Rename document</Menubar.ItemLabel><Menubar.Description>Change the title visible to collaborators.</Menubar.Description><Menubar.Shortcut>⌘R</Menubar.Shortcut></Menubar.Item><Menubar.Item disabled value="publish"><Menubar.ItemLabel>Publish unavailable</Menubar.ItemLabel></Menubar.Item></Menubar.Group><Menubar.Separator /><Menubar.Item tone="danger" value="delete"><Menubar.ItemLabel>Delete document</Menubar.ItemLabel></Menubar.Item></Menubar.Content></Menubar.Menu></Menubar.Root></EvidenceSurface></Scenario>
    <Scenario {...menubarScenarios[5]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="menubar-selection"><Cell label="selection"><Menubar.Root aria-label="View commands"><Menubar.Menu value="view"><Menubar.Trigger>View</Menubar.Trigger><Menubar.Content ariaLabel="View commands"><Menubar.CheckboxItem checked={lineNumbers} onCheckedChange={(next) => setLineNumbers(next === true)} value="lines"><Menubar.ItemIndicator /><Menubar.ItemLabel>Line numbers</Menubar.ItemLabel></Menubar.CheckboxItem><Menubar.CheckboxItem checked="indeterminate" value="guides"><Menubar.ItemIndicator /><Menubar.ItemLabel>Inherited guides</Menubar.ItemLabel></Menubar.CheckboxItem><Menubar.RadioGroup value={theme} onValueChange={setTheme}>{["light", "dark", "system"].map((value) => <Menubar.RadioItem key={value} value={value}><Menubar.ItemIndicator /><Menubar.ItemLabel>{value[0].toUpperCase() + value.slice(1)}</Menubar.ItemLabel></Menubar.RadioItem>)}</Menubar.RadioGroup></Menubar.Content></Menubar.Menu></Menubar.Root></Cell><Cell label="submenu"><Menubar.Root aria-label="Insert commands"><Menubar.Menu value="insert"><Menubar.Trigger>Insert</Menubar.Trigger><Menubar.Content ariaLabel="Insert commands"><Menubar.Sub><Menubar.SubTrigger value="media"><Menubar.ItemLabel>Media</Menubar.ItemLabel></Menubar.SubTrigger><Menubar.SubContent><Menubar.Item value="image"><Menubar.ItemLabel>Image</Menubar.ItemLabel></Menubar.Item><Menubar.Item value="video"><Menubar.ItemLabel>Video</Menubar.ItemLabel></Menubar.Item></Menubar.SubContent></Menubar.Sub></Menubar.Content></Menubar.Menu></Menubar.Root></Cell></Grid.Root></Scenario>
    <Scenario {...menubarScenarios[6]}><VStack className="menu-evidence-stack" data-testid="menubar-composition"><Group title="Rendered output" description="The root remains one labeled menubar and each category Trigger remains its menuitem button."><RenderedOutput label="Menubar HTML"><Menubar.Root aria-label="Composed commands" render={<div data-adapter="editor-menubar" />}><Menubar.Menu value="file"><Menubar.Trigger asChild><button data-adapter="file-command">File</button></Menubar.Trigger><Menubar.Content><Menubar.Item value="new">New</Menubar.Item></Menubar.Content></Menubar.Menu></Menubar.Root></RenderedOutput></Group></VStack></Scenario>
    <Scenario {...menubarScenarios[7]}><VStack className="menu-evidence-stack"><Group title="Scoped appearances" description="The same command strip and popup recipe inherit local light and dark tokens."><Grid.Root columns={2} className="menu-scoped-grid" data-testid="menubar-appearance"><EvidenceSurface className="menu-scoped-panel" data-brick-appearance="light"><Code>light</Code><EditorMenubar /></EvidenceSurface><EvidenceSurface className="menu-scoped-panel" data-brick-appearance="dark"><Code>dark</Code><EditorMenubar /></EvidenceSurface></Grid.Root></Group><Group title="Consumer customization" description="The shown Root variables produce exactly the purple strip and active command preview."><EvidenceSurface className="menu-customization" inset="lg"><PlaygroundCodeBlock aria-label="Menubar customization code">{`style={{\n  "--brick-menubar-background": "#f5f3ff",\n  "--brick-menubar-border": "#8b5cf6",\n  "--brick-menubar-trigger-open-background": "#ddd6fe",\n  "--brick-menubar-trigger-open-foreground": "#5b21b6",\n}}`}</PlaygroundCodeBlock><div className="menu-customization__preview"><EditorMenubar defaultValue="file" style={customStyle} /></div></EvidenceSurface></Group></VStack></Scenario>
    <Scenario {...menubarScenarios[8]}><Grid.Root columns={2} className="menu-grid menu-grid--two" data-testid="menubar-stress"><Cell label="narrow explicit overflow"><div className="menu-phone" style={{ overflowX: "auto" }}><Menubar.Root aria-label="Narrow editor commands"><Menubar.Menu value="file"><Menubar.Trigger>File</Menubar.Trigger><Menubar.Content><Menubar.Item value="new">New</Menubar.Item></Menubar.Content></Menubar.Menu><Menubar.Menu value="edit"><Menubar.Trigger>Edit</Menubar.Trigger><Menubar.Content><Menubar.Item value="undo">Undo</Menubar.Item></Menubar.Content></Menubar.Menu><Menubar.Menu value="selection"><Menubar.Trigger>Selection</Menubar.Trigger><Menubar.Content><Menubar.Item value="all">Select all</Menubar.Item></Menubar.Content></Menubar.Menu><Menubar.Menu value="view"><Menubar.Trigger>View</Menubar.Trigger><Menubar.Content><Menubar.Item value="zoom">Zoom</Menubar.Item></Menubar.Content></Menubar.Menu></Menubar.Root></div></Cell><Cell label="RTL"><div dir="rtl"><Menubar.Root aria-label="أوامر المحرر" dir="rtl"><Menubar.Menu value="file"><Menubar.Trigger>ملف</Menubar.Trigger><Menubar.Content><Menubar.Item value="new"><Menubar.ItemLabel>ملف جديد</Menubar.ItemLabel></Menubar.Item></Menubar.Content></Menubar.Menu><Menubar.Menu value="edit"><Menubar.Trigger>تحرير</Menubar.Trigger><Menubar.Content><Menubar.Item value="undo"><Menubar.ItemLabel>تراجع</Menubar.ItemLabel></Menubar.Item></Menubar.Content></Menubar.Menu></Menubar.Root></div></Cell></Grid.Root></Scenario>
  </VStack>;
}
