import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test.beforeEach(async ({ page }) => { await page.goto("/navigation-menu"); });

test("defaults, links, disclosure, sizes, orientation, state, and composition work", async ({ page }) => {
  const root = page.getByTestId("navigation-menu-overview").getByRole("navigation", { name: "Primary navigation" });
  await expect(root).toHaveAttribute("data-size", "md");
  await expect(root.getByRole("button", { name: "Products" })).toHaveCSS("min-height", "44px");
  const products = root.getByRole("button", { name: "Products" });
  await expect(products).toHaveAttribute("aria-expanded", "false");
  await products.click();
  await expect(products).toHaveAttribute("aria-expanded", "true");
  const panelLink = root.getByRole("link", { name: /Analytics/ });
  const panelSurface = panelLink.locator(":scope > .brick-surface");
  await expect(panelLink).toHaveAttribute("data-variant", "panel");
  await expect(panelLink).toHaveCSS("white-space", "normal");
  await expect(panelLink).toHaveCSS("padding", "0px");
  await expect(panelSurface).toHaveCSS("padding", "12px");
  await expect(panelSurface).toHaveAttribute("data-level", "subtle");
  const [panelLinkBox, panelSurfaceBox] = await Promise.all([panelLink.boundingBox(), panelSurface.boundingBox()]);
  expect(panelLinkBox?.width).toBeGreaterThan(0);
  expect(panelLinkBox?.width).toBeCloseTo(panelSurfaceBox?.width ?? 0, 0);
  await products.focus();
  await page.keyboard.press("Tab");
  await panelLink.focus();
  await expect(panelLink).toBeFocused();
  await expect(panelSurface).toHaveCSS("outline-style", "solid");
  const indicator = root.locator(".brick-navigation-menu__indicator");
  const indicatorArrow = indicator.locator(".brick-navigation-menu__indicator-arrow");
  const viewport = root.locator(".brick-navigation-menu__viewport");
  await expect(indicator).toHaveAttribute("data-state", "visible");
  await expect(indicatorArrow).toHaveCSS("width", "10px");
  await expect(indicatorArrow).toHaveCSS("height", "6px");
  const triggerChevron = await products.evaluate((element) => {
    const style = getComputedStyle(element, "::after");
    return { gap: getComputedStyle(element).gap, size: style.width, stroke: style.borderRightWidth };
  });
  expect(triggerChevron).toEqual({ gap: "6px", size: "6px", stroke: "1px" });
  const current = root.getByRole("link", { name: "Pricing" });
  await expect(current).toHaveAttribute("data-active", "");
  await expect(current).toHaveCSS("text-decoration-thickness", "1px");
  const [triggerBox, indicatorBox, indicatorArrowBox, viewportBox] = await Promise.all([products.boundingBox(), indicator.boundingBox(), indicatorArrow.boundingBox(), viewport.boundingBox()]);
  expect(indicatorBox && viewportBox && indicatorBox.y + indicatorBox.height).toBeCloseTo(viewportBox?.y ?? 0, 0);
  if (!triggerBox || !viewportBox) throw new Error("Horizontal Navigation Menu geometry is not measurable.");
  const visibleBoundary = await page.evaluate(() => ({ left: window.visualViewport?.offsetLeft ?? 0, width: window.visualViewport?.width ?? document.documentElement.clientWidth }));
  const boundaryStart = visibleBoundary.left + 8;
  const boundaryEnd = visibleBoundary.left + visibleBoundary.width - 8;
  const preferredLeft = triggerBox.x + triggerBox.width / 2 - viewportBox.width / 2;
  const expectedLeft = Math.min(Math.max(preferredLeft, boundaryStart), boundaryEnd - viewportBox.width);
  expect(viewportBox.x).toBeCloseTo(expectedLeft, 0);
  expect(indicatorArrowBox && viewportBox && indicatorArrowBox.x + indicatorArrowBox.width / 2).toBeGreaterThanOrEqual(viewportBox?.x ?? 0);
  expect(indicatorArrowBox && viewportBox && indicatorArrowBox.x + indicatorArrowBox.width / 2).toBeLessThanOrEqual((viewportBox?.x ?? 0) + (viewportBox?.width ?? 0));
  for (const [index, size] of ["sm", "md", "lg"].entries()) {
    const sizedRoot = page.getByTestId("navigation-menu-size").locator(`.brick-navigation-menu[data-size='${size}']`);
    await expect(sizedRoot).toHaveCount(1);
    await expect(sizedRoot.getByRole("button").first()).toHaveCSS("min-height", ["32px", "44px", "48px"][index]);
  }
  const verticalRoot = page.getByTestId("navigation-menu-orientation").locator(".brick-navigation-menu[data-orientation='vertical']");
  await expect(page.getByTestId("navigation-menu-orientation").locator(".menu-cell").first().locator(".brick-navigation-menu[data-orientation='vertical']")).toHaveCount(1);
  const verticalProducts = verticalRoot.getByRole("button", { name: "Products" });
  await verticalProducts.click();
  const verticalIndicator = verticalRoot.locator(".brick-navigation-menu__indicator");
  const verticalViewport = verticalRoot.locator(".brick-navigation-menu__viewport");
  await expect(verticalIndicator).toHaveAttribute("data-state", "visible");
  const verticalArrow = verticalIndicator.locator(".brick-navigation-menu__indicator-arrow");
  await expect(verticalArrow).toBeVisible();
  await expect(verticalArrow).toHaveCSS("width", "6px");
  await expect(verticalArrow).toHaveCSS("height", "10px");
  const [verticalTriggerBox, verticalIndicatorBox, verticalArrowBox, verticalViewportBox] = await Promise.all([verticalProducts.boundingBox(), verticalIndicator.boundingBox(), verticalArrow.boundingBox(), verticalViewport.boundingBox()]);
  expect(verticalIndicatorBox && verticalViewportBox && verticalIndicatorBox.x + verticalIndicatorBox.width).toBeCloseTo(verticalViewportBox?.x ?? 0, 0);
  expect(verticalTriggerBox && verticalArrowBox && verticalArrowBox.y + verticalArrowBox.height / 2).toBeCloseTo((verticalTriggerBox?.y ?? 0) + (verticalTriggerBox?.height ?? 0) / 2, 0);
  expect(verticalTriggerBox && verticalViewportBox && verticalViewportBox.y).toBeCloseTo(verticalTriggerBox?.y ?? 0, 0);
  const verticalSolutions = verticalRoot.getByRole("button", { name: "Solutions" });
  await verticalSolutions.click();
  await expect(verticalSolutions).toHaveAttribute("aria-expanded", "true");
  await expect.poll(async () => {
    const [solutionTriggerBox, solutionArrowBox, solutionViewportBox] = await Promise.all([verticalSolutions.boundingBox(), verticalArrow.boundingBox(), verticalViewport.boundingBox()]);
    if (!solutionTriggerBox || !solutionArrowBox || !solutionViewportBox) return false;
    const arrowCenter = solutionArrowBox.y + solutionArrowBox.height / 2;
    return Math.abs(solutionViewportBox.y - solutionTriggerBox.y) <= 1 && arrowCenter >= solutionViewportBox.y && arrowCenter <= solutionViewportBox.y + solutionViewportBox.height;
  }).toBe(true);
  const direct = page.getByRole("navigation", { name: "Direct destinations" });
  await expect(direct.getByRole("link", { name: "Overview" })).toHaveAttribute("href", "/overview");
  const disabled = page.getByRole("navigation", { name: "Unavailable destination" }).getByRole("button", { name: "Products" });
  await expect(disabled).toBeDisabled();
  await expect(page.locator("[data-router-link='docs']")).toHaveAttribute("aria-current", "page");
  const panelFallback = page.getByTestId("navigation-menu-panel-fallback");
  await page.keyboard.press("Tab");
  await panelFallback.focus();
  await expect(panelFallback).toBeFocused();
  expect(await panelFallback.evaluate((element) => element.matches(":focus-visible"))).toBe(true);
  await expect(panelFallback).toHaveCSS("outline-style", "solid");
});

test("keyboard, mobile replacement, RTL, and accessibility work", async ({ page }) => {
  const links = page.getByRole("navigation", { name: "Direct destinations" });
  const overview = links.getByRole("link", { name: "Overview" }); await overview.focus(); await overview.press("ArrowRight");
  await expect(links.getByRole("link", { name: "Pricing" })).toBeFocused();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("button", { name: "Open mobile navigation" })).toBeVisible();
  const rtl = page.getByRole("navigation", { name: "التنقل الرئيسي" });
  const products = rtl.getByRole("button", { name: "المنتجات" });
  await products.click();
  const rtlArrow = rtl.locator(".brick-navigation-menu__indicator-arrow");
  const rtlViewport = rtl.locator(".brick-navigation-menu__viewport");
  await expect(rtlArrow).toBeVisible();
  await expect.poll(async () => {
    const [rtlTriggerBox, rtlArrowBox, rtlViewportBox] = await Promise.all([products.boundingBox(), rtlArrow.boundingBox(), rtlViewport.boundingBox()]);
    if (!rtlTriggerBox || !rtlArrowBox || !rtlViewportBox) return false;
    const triggerCenter = rtlTriggerBox.x + rtlTriggerBox.width / 2;
    const arrowCenter = rtlArrowBox.x + rtlArrowBox.width / 2;
    return Math.abs(triggerCenter - arrowCenter) <= 1 && arrowCenter >= rtlViewportBox.x && arrowCenter <= rtlViewportBox.x + rtlViewportBox.width;
  }).toBe(true);
  await page.keyboard.press("Escape");
  await products.focus(); await products.press("ArrowLeft");
  await expect(rtl.getByRole("link", { name: "الأسعار" })).toBeFocused();
  expect((await new AxeBuilder({ page }).include('[data-testid="navigation-menu-overview"]').analyze()).violations).toEqual([]);
});
