// Generated by scripts/generate-aspect-ratios.mjs from tokens.tokens.json.
/** Stable standard proportions; numeric values, not runtime theme lookups. */
export const aspectRatios = Object.freeze({
  "square": 1,
  "landscape": 1.3333333333333333,
  "portrait": 0.75,
  "wide": 1.7777777777777777,
  "ultrawide": 3.6,
  "golden": 1.618
} as const);
export type AspectRatioToken = keyof typeof aspectRatios;
