export interface PlaygroundEntry {
  category: string;
  description: string;
  id: string;
  route: string;
  title: string;
}

export const componentEntries = [
  {
    category: "Layout",
    description: "Explicit light, dark, and inherited semantic-token scopes.",
    id: "appearance",
    route: "/appearance",
    title: "Appearance",
  },
  {
    category: "Layout",
    description: "CSS-only content shown from a fixed viewport breakpoint.",
    id: "show",
    route: "/show",
    title: "Show",
  },
  {
    category: "Layout",
    description: "CSS-only content hidden from a fixed viewport breakpoint.",
    id: "hide",
    route: "/hide",
    title: "Hide",
  },
  {
    category: "Layout",
    description: "Stable ratio geometry and restrained framing for authored content.",
    id: "aspect-ratio",
    route: "/aspect-ratio",
    title: "Aspect Ratio",
  },
  {
    category: "Actions",
    description: "Finished actions with native Button semantics.",
    id: "button",
    route: "/button",
    title: "Button",
  },
  {
    category: "Actions",
    description: "Compact named actions and links.",
    id: "icon-button",
    route: "/icon-button",
    title: "Icon Button",
  },
  {
    category: "Navigation",
    description: "Application-level header structure and surfaces.",
    id: "app-bar",
    route: "/app-bar",
    title: "App Bar",
  },
  {
    category: "Navigation",
    description: "Inline and standalone native navigation.",
    id: "link",
    route: "/link",
    title: "Link",
  },
  {
    category: "Navigation",
    description: "One native destination expanded across a containing region.",
    id: "link-box",
    route: "/link-box",
    title: "Link Box",
  },
  {
    category: "Navigation",
    description: "Hierarchical page location and ancestor navigation.",
    id: "breadcrumb",
    route: "/breadcrumb",
    title: "Breadcrumb",
  },
  {
    category: "Navigation",
    description: "Related peer panels with complete keyboard navigation.",
    id: "tabs",
    route: "/tabs",
    title: "Tabs",
  },
  {
    category: "Actions",
    description: "Button-triggered temporary commands and settings.",
    id: "dropdown-menu",
    route: "/dropdown-menu",
    title: "Dropdown Menu",
  },
  {
    category: "Actions",
    description: "Supplemental target commands for pointer, keyboard, and touch.",
    id: "context-menu",
    route: "/context-menu",
    title: "Context Menu",
  },
  {
    category: "Actions",
    description: "Persistent application command categories and popups.",
    id: "menubar",
    route: "/menubar",
    title: "Menubar",
  },
  {
    category: "Navigation",
    description: "Native site destinations with coordinated disclosure panels.",
    id: "navigation-menu",
    route: "/navigation-menu",
    title: "Navigation Menu",
  },
  {
    category: "Navigation",
    description: "Compact, persistent top-level destinations for narrow layouts.",
    id: "bottom-navigation",
    route: "/bottom-navigation",
    title: "Bottom Navigation",
  },
  {
    category: "Navigation",
    description: "Finished destination lists, sections, and disclosure.",
    id: "nav-list",
    route: "/nav-list",
    title: "Nav List",
  },
  {
    category: "Layout",
    description: "Persistent complementary panel and coordinated main content.",
    id: "sidebar",
    route: "/sidebar",
    title: "Sidebar",
  },
  {
    category: "Data display",
    description: "Semantic text with finished visual typography.",
    id: "text",
    route: "/text",
    title: "Text",
  },
  {
    category: "Data display",
    description: "Compact authored values with an optional explicit remove action.",
    id: "chip",
    route: "/chip",
    title: "Chip",
  },
  {
    category: "Data display",
    description: "Sized, semantic, accessible SVG presentation.",
    id: "icon",
    route: "/icon",
    title: "Icon",
  },
  {
    category: "Accessibility",
    description: "Assistive text without a visual layout footprint.",
    id: "visually-hidden",
    route: "/visually-hidden",
    title: "Visually Hidden",
  },
  {
    category: "Accessibility",
    description: "Visible-on-focus bypass navigation with a paired content target.",
    id: "skip-link",
    route: "/skip-link",
    title: "Skip Link",
  },
  {
    category: "Data display",
    description: "Responsive media with authored fallback and finished framing.",
    id: "image",
    route: "/image",
    title: "Image",
  },
  {
    category: "Data display",
    description: "Native ordered and unordered content with structured rows.",
    id: "list",
    route: "/list",
    title: "List",
  },
  {
    category: "Actions",
    description: "Manual linear ordering with drag, keyboard, touch, and direct movement.",
    id: "reorderable-list",
    route: "/reorderable-list",
    title: "Reorderable List",
  },
  {
    category: "Data display",
    description: "Native static tabular data with responsive containment.",
    id: "table",
    route: "/table",
    title: "Table",
  },
  {
    category: "Data display",
    description: "Navigable tabular data with row selection and sortable headers.",
    id: "data-grid",
    route: "/data-grid",
    title: "Data Grid",
  },
  {
    category: "Data display",
    description: "Navigable hierarchical rows with independently focusable cells.",
    id: "tree-grid",
    route: "/tree-grid",
    title: "Tree Grid",
  },
  {
    category: "Data display",
    description: "A finished one-dimensional hierarchical selection widget.",
    id: "tree",
    route: "/tree",
    title: "Tree",
  },
  {
    category: "Data display",
    description: "Dynamic rich article streams with article-by-article keyboard navigation.",
    id: "feed",
    route: "/feed",
    title: "Feed",
  },
  {
    category: "Actions",
    description: "Item-level quick actions revealed by swipe with a visible alternative.",
    id: "swipeable-item",
    route: "/swipeable-item",
    title: "Swipeable Item",
  },
  {
    category: "Actions",
    description: "Related commands with one keyboard entry point.",
    id: "toolbar",
    route: "/toolbar",
    title: "Toolbar",
  },
  {
    category: "Navigation",
    description: "Bounded numbered-page navigation with generated ranges.",
    id: "pagination",
    route: "/pagination",
    title: "Pagination",
  },
  {
    category: "Data display",
    description: "One-slide sequences with optional controls and rotation.",
    id: "carousel",
    route: "/carousel",
    title: "Carousel",
  },
  {
    category: "Data display",
    description: "Inline technical literals with native code semantics.",
    id: "code",
    route: "/code",
    title: "Code",
  },
  {
    category: "Content and status",
    description: "Native stress emphasis that inherits surrounding typography.",
    id: "em",
    route: "/em",
    title: "Em",
  },
  {
    category: "Content and status",
    description: "Static native relevance with closed theme-aware recipes.",
    id: "mark",
    route: "/mark",
    title: "Mark",
  },
  {
    category: "Content and status",
    description: "Native keyboard-input notation with compact finished recipes.",
    id: "kbd",
    route: "/kbd",
    title: "Kbd",
  },
  {
    category: "Content and status",
    description: "Extended quotations with semantic source and attribution structure.",
    id: "blockquote",
    route: "/blockquote",
    title: "Blockquote",
  },
  {
    category: "Content and status",
    description: "Exact plain-text query matching with finished semantic relevance paint.",
    id: "highlight",
    route: "/highlight",
    title: "Highlight",
  },
  {
    category: "Content and status",
    description: "Editorial descendant typography, rhythm, and readable measure for trusted React content.",
    id: "prose",
    route: "/prose",
    title: "Prose",
  },
  {
    category: "Data display",
    description: "Structured source, overflow, language, and copy.",
    id: "code-block",
    route: "/code-block",
    title: "Code Block",
  },
  {
    category: "Layout",
    description: "Tokenized one-dimensional rows and columns.",
    id: "stack",
    route: "/stack",
    title: "Stack",
  },
  {
    category: "Layout",
    description: "Compact inline clusters with optional attached borders and logical corners.",
    id: "group",
    route: "/group",
    title: "Group",
  },
  {
    category: "Data display",
    description: "Native term-and-value facts with responsive alignment.",
    id: "data-list",
    route: "/data-list",
    title: "Data List",
  },
  {
    category: "Layout",
    description: "Source-ordered depth layout and nine-position placement.",
    id: "z-stack",
    route: "/z-stack",
    title: "ZStack",
  },
  {
    category: "Layout",
    description: "Tokenized two-dimensional tracks and item placement.",
    id: "grid",
    route: "/grid",
    title: "Grid",
  },
  {
    category: "Layout",
    description: "Centered content measures and logical page gutters.",
    id: "container",
    route: "/container",
    title: "Container",
  },
  {
    category: "Layout",
    description: "Themeable responsive rhythm for major page regions.",
    id: "section",
    route: "/section",
    title: "Section",
  },
  {
    category: "Layout",
    description: "Responsive logical size constraints for one local element.",
    id: "frame",
    route: "/frame",
    title: "Frame",
  },
  {
    category: "Layout",
    description: "Responsive logical negative margins for deliberate edge media.",
    id: "bleed",
    route: "/bleed",
    title: "Bleed",
  },
  {
    category: "Layout",
    description: "Neutral surface levels, borders, elevation, radius, and inset.",
    id: "surface",
    route: "/surface",
    title: "Surface",
  },
  {
    category: "Data display",
    description: "Decorative and semantic structural separators.",
    id: "divider",
    route: "/divider",
    title: "Divider",
  },
  {
    category: "Layout",
    description: "Constrained native scrolling with explicit axes and visibility.",
    id: "scroll-area",
    route: "/scroll-area",
    title: "Scroll Area",
  },
  {
    category: "Data display",
    description: "Static grouped content with finished surfaces.",
    id: "card",
    route: "/card",
    title: "Card",
  },
  {
    category: "Feedback",
    description: "Motion-safe placeholders that preserve loading layout.",
    id: "skeleton",
    route: "/skeleton",
    title: "Skeleton",
  },
  {
    category: "Feedback",
    description: "Determinate, indeterminate, and buffered linear task progress.",
    id: "progress",
    route: "/progress",
    title: "Progress",
  },
  {
    category: "Feedback",
    description: "Compact determinate and indeterminate circular task progress.",
    id: "progress-circle",
    route: "/progress-circle",
    title: "Progress Circle",
  },
  {
    category: "Forms",
    description: "Single-value and range input with markers, formatting, and directional geometry.",
    id: "slider",
    route: "/slider",
    title: "Slider",
  },
  {
    category: "Forms",
    description: "Single-slider rating input with proportional decorative artwork.",
    id: "rating",
    route: "/rating",
    title: "Rating",
  },
  {
    category: "Forms",
    description: "File picker and drop target with validation and removable selected-file items.",
    id: "file-upload",
    route: "/file-upload",
    title: "File Upload",
  },
  {
    category: "Feedback",
    description: "Temporary non-blocking application outcomes and process updates.",
    id: "toast",
    route: "/toast",
    title: "Toast",
  },
  {
    category: "Data display",
    description: "One independent in-flow disclosure with finished motion and surfaces.",
    id: "collapsible",
    route: "/collapsible",
    title: "Collapsible",
  },
  {
    category: "Data display",
    description: "A coordinated set of accessible disclosure items in one or multiple selection modes.",
    id: "accordion",
    route: "/accordion",
    title: "Accordion",
  },
  {
    category: "Overlays",
    description: "Focused modal tasks and decisions.",
    id: "dialog",
    route: "/dialog",
    title: "Dialog",
  },
  {
    category: "Overlays",
    description: "Urgent modal confirmation.",
    id: "alert-dialog",
    route: "/alert-dialog",
    title: "Alert Dialog",
  },
  {
    category: "Overlays",
    description: "Edge-attached modal content.",
    id: "drawer",
    route: "/drawer",
    title: "Drawer",
  },
  {
    category: "Data display",
    description: "Passive status and category labels.",
    id: "badge",
    route: "/badge",
    title: "Badge",
  },
  {
    category: "Data display",
    description: "Contextual counts and notification dots.",
    id: "notification-badge",
    route: "/notification-badge",
    title: "Notification Badge",
  },
  {
    category: "Data display",
    description: "Identity imagery, fallback, and status.",
    id: "avatar",
    route: "/avatar",
    title: "Avatar",
  },
  {
    category: "Data display",
    description: "Passive semantic state with a dot and visible label.",
    id: "status",
    route: "/status",
    title: "Status",
  },
  {
    category: "Data display",
    description: "Passive solid, alpha-aware, and mixed color previews.",
    id: "color-swatch",
    route: "/color-swatch",
    title: "Color Swatch",
  },
  {
    category: "Forms",
    description: "Opaque hexadecimal editing, native chooser, presets, and submission.",
    id: "color-picker",
    route: "/color-picker",
    title: "Color Picker",
  },
  {
    category: "Actions",
    description: "Standalone pressed-state actions.",
    id: "toggle",
    route: "/toggle",
    title: "Toggle",
  },
  {
    category: "Actions",
    description: "Single and multiple grouped toggles.",
    id: "toggle-group",
    route: "/toggle-group",
    title: "Toggle Group",
  },
  {
    category: "Overlays",
    description: "Supplemental noninteractive labels.",
    id: "tooltip",
    route: "/tooltip",
    title: "Tooltip",
  },
  {
    category: "Overlays",
    description: "Preview content for genuine links.",
    id: "hover-card",
    route: "/hover-card",
    title: "Hover Card",
  },
  {
    category: "Overlays",
    description: "Intentional compact floating interaction.",
    id: "popover",
    route: "/popover",
    title: "Popover",
  },
  {
    category: "Forms",
    description: "Finished native single-line text entry.",
    id: "input",
    route: "/input",
    title: "Input",
  },
  {
    category: "Forms",
    description: "Numeric entry with bounded stepping and native form participation.",
    id: "number-input",
    route: "/number-input",
    title: "Number Input",
  },
  {
    category: "Forms",
    description: "Segmented one-time-code entry with paste and completion behavior.",
    id: "otp-field",
    route: "/otp-field",
    title: "OTP Field",
  },
  {
    category: "Forms",
    description: "Password entry with an explicitly named visibility action.",
    id: "password-toggle-field",
    route: "/password-toggle-field",
    title: "Password Toggle Field",
  },
  {
    category: "Forms",
    description: "Finished native multi-line text entry.",
    id: "textarea",
    route: "/textarea",
    title: "Textarea",
  },
  {
    category: "Forms",
    description: "Finished single-value select-only choice control.",
    id: "select",
    route: "/select",
    title: "Select",
  },
  {
    category: "Forms",
    description: "Searchable single-value choice with optional free text.",
    id: "combobox",
    route: "/combobox",
    title: "Combobox",
  },
  {
    category: "Forms",
    description: "Compact selection of several predefined values.",
    id: "multi-select",
    route: "/multi-select",
    title: "Multi Select",
  },
  {
    category: "Forms",
    description: "Styled native form submission boundary.",
    id: "form",
    route: "/form",
    title: "Form",
  },
  {
    category: "Forms",
    description: "One labeled control and its messages.",
    id: "field",
    route: "/field",
    title: "Field",
  },
  {
    category: "Forms",
    description: "Native related-control grouping.",
    id: "fieldset",
    route: "/fieldset",
    title: "Fieldset",
  },
  {
    category: "Forms",
    description: "Standalone binary and mixed selection.",
    id: "checkbox",
    route: "/checkbox",
    title: "Checkbox",
  },
  {
    category: "Forms",
    description: "Related checkbox selection and parent state.",
    id: "checkbox-group",
    route: "/checkbox-group",
    title: "Checkbox Group",
  },
  {
    category: "Forms",
    description: "Finished single-selection choice groups.",
    id: "radio-group",
    route: "/radio-group",
    title: "Radio Group",
  },
  {
    category: "Controls",
    description: "Compact radio-semantic mode choices with a moving indicator.",
    id: "segment-group",
    route: "/segment-group",
    title: "Segment Group",
  },
  {
    category: "Forms",
    description: "Immediate binary settings.",
    id: "switch",
    route: "/switch",
    title: "Switch",
  },
] as const satisfies readonly PlaygroundEntry[];

export const playgroundEntries: readonly PlaygroundEntry[] = componentEntries;

export function resolvePlaygroundEntry(path: string): PlaygroundEntry {
  return (
    componentEntries.find((entry) => entry.route === (path === "/components/feed" ? "/feed" : path)) ??
    componentEntries[0]
  );
}
